#!/usr/bin/env python3
"""Batch-generate Authors and Books to reach 400+ each."""
import json
from pathlib import Path

TOPICS_DIR = Path("app/src/main/assets/topics")

def mk(cat, subtype, name, teaser, byline, target, mins, instr, tags, slug, tier=2):
    e = {"id":f"{'author' if cat=='AUTHORS' else 'book'}-{slug}","categoryId":cat,
         "subtype":subtype,"name":name,"teaser":teaser,"imageUrl":""}
    if byline: e["byline"] = byline
    e["exploreAction"] = {"verb":"Read","targetName":target,
                           "durationMinutes":mins,"instruction":instr}
    e["tags"] = tags; e["tier"] = tier; return e

def append_batch(fname, batch, cat):
    path = TOPICS_DIR / fname
    existing = json.loads(path.read_text())
    ids = {e["id"] for e in existing}
    new = [e for e in batch if e["id"] not in ids]
    if not new: print(f"  {fname}: skipped ({len(batch)} dupes)"); return 0
    existing.extend(new)
    path.write_text(json.dumps(existing, indent=2, ensure_ascii=False) + "\n")
    print(f"  {fname}: +{len(new)} → {len(existing)}")
    for e in new:
        assert e["id"] and e["name"] and e["teaser"]
        assert e["categoryId"] == cat
    return len(new)

def count(fname):
    return len(json.loads((TOPICS_DIR / fname).read_text()))

print(f"Authors before: {count('authors.json')} | Books before: {count('books.json')}")

# Run batches
added = 0

# ======================
# AUTHORS BATCH (40)
# ======================
authors_batch = [
mk("AUTHORS","Author","James Baldwin","Publishing 'Giovanni's Room' (1956), his publisher told him to burn it — it would ruin his career. He published anyway. His essay 'The Fire Next Time' was written as a letter to his 14-year-old nephew.","","The Fire Next Time, first essay",25,"Read the opening essay. Baldwin addresses his nephew James, named after him. Every paragraph moves between love and fury in the same sentence — notice how he writes about anger without ever losing tenderness.",["American","Fiction","Essays","20th Century"],"james-baldwin"),

mk("AUTHORS","Author","Octavia Butler","First sci-fi writer to win a MacArthur Genius Grant. Her 1993 novel 'Parable of the Sower' predicted a 2020s America wrecked by climate change and a populist promising 'Make America Great Again.' She started writing at 10 and an aunt told her Black people couldn't be writers.","","Parable of the Sower, first 3 chapters",30,"Read the opening. Lauren Olamina starts a religion called Earthseed whose first verse is 'God is Change.' Written in 1993, it reads like our present. The diary format makes dystopia intimate — each entry starts with a date and a verse.",["American","Science Fiction","Afrofuturism","20th Century"],"octavia-butler"),

mk("AUTHORS","Author","Italo Calvino","Fought as a partisan in WWII then spent his career writing fiction that reads like math — 'Invisible Cities' has Marco Polo describing 55 impossible cities to Kublai Khan. Died the week before he was supposed to give the Harvard Norton Lectures (1985).","","Invisible Cities, any 5 cities",22,"Read five cities from Invisible Cities. Each is one page, numbered and thematic. Polo describes them to the Khan. They're probably all Venice described differently. You can read the book in any order and it still works — it's built like a crystal.",["Italian","Fiction","Postmodern","20th Century"],"italo-calvino"),

mk("AUTHORS","Author","Elena Ferrante","The world's most famous anonymous author — 15+ million copies sold, zero public appearances, only written interviews. Her Neapolitan Novels trace two women's friendship from 1950s Naples to the present. Her identity remains unknown.","","My Brilliant Friend, prologue + first chapter",25,"Read the prologue and first chapter. Lila has vanished, and Elena is writing their whole history out of spite. Childhood is built through small violences: a doll in a cellar, a broken arm, a race to be first. Ferrante makes the neighborhood feel like a planet.",["Italian","Fiction","Contemporary","21st Century"],"elena-ferrante"),

mk("AUTHORS","Author","W.G. Sebald","German writer who lived in England, making novels that are half-text and half-blurry photos — none captioned, none prove anything. 'The Rings of Saturn' is about walking the Suffolk coast and somehow also covers imperialism, silkworms, and Joseph Conrad.","","The Rings of Saturn, first chapter",20,"Read the first chapter. Sebald walks the Suffolk coast and within two pages you're reading about Thomas Browne's skull, Rembrandt's Anatomy Lesson, and the fishing industry. His sentences are so long you forget how they started. The photos feel like evidence that's hiding something.",["German","Fiction","Essays","20th Century"],"wg-sebald"),
]
added += append_batch("authors.json", authors_batch, "AUTHORS")

# ======================
# BOOKS BATCH (40)
# ======================
books_batch = [
mk("BOOKS","Book","The Handmaid's Tale (1985)","Margaret Atwood wrote this dystopia in West Berlin during the Cold War — every detail was based on something that had actually happened somewhere in history. The handmaids' red robes? Biblical. The ceremonial rape? Enslaved women in the American South. The book has been banned more than any other in American schools.","Margaret Atwood","The Handmaid's Tale, chapters 1-5",35,"Read the first five chapters. Offred narrates in present tense from a single room, describing how she got here through fragments. Notice the shop signs are pictures — handmaids aren't allowed to read. The power of the novel is what she doesn't say: her real name is never revealed.",["Canadian","Dystopian","Feminist","20th Century","1980s"],"the-handmaids-tale"),

mk("BOOKS","Book","If on a Winter's Night a Traveler (1979)","Italo Calvino's novel that starts in the second person — 'You are about to begin reading Italo Calvino's new novel' — and then keeps restarting. The Reader (you) is the protagonist. Every chapter is the first chapter of a different book that the Reader can never finish because of some absurd publishing error.","Italo Calvino","If on a Winter's Night a Traveler, the first two chapters",20,"Read the first two chapters. Chapter 1 addresses 'you' directly — you buy the book, you start reading. Chapter 2 is the first chapter of a completely different novel. Calvino invented 10 different opening paragraphs for 10 imaginary books, each in a different genre. Notice how the second-person address makes you complicit.",["Italian","Postmodern","Metafiction","20th Century"],"if-on-a-winters-night"),

mk("BOOKS","Book","The Left Hand of Darkness (1969)","Ursula K. Le Guin's novel about an ambassador sent to a planet where people have no fixed gender — they become male or female only during mating. Published in 1969, it was one of the first sci-fi books to treat gender as a social construct. Le Guin later said she wrote it to find out what a man would be like without the 'noise' of gender.","Ursula K. Le Guin","The Left Hand of Darkness, first 40 pages",30,"Read the opening. Genly Ai, a black man from Earth, arrives on the ice planet Gethen as an envoy. The Gethenians find him 'a pervert' because he's always one gender. Le Guin wrote the novel alternating between Ai's report and Gethenian folklore. Notice how cold defines every sentence.",["American","Science Fiction","Feminist","20th Century"],"the-left-hand-of-darkness"),

mk("BOOKS","Book","The Remains of the Day (1989)","Kazuo Ishiguro's novel about a butler on a road trip through the English countryside, looking back on his decades of perfect service at Darlington Hall. The butler, Stevens, is so repressed that his narration is a study in self-deception — you understand what he's feeling by what he refuses to say. Won the Booker Prize. Ishiguro wrote it in 4 weeks.","Kazuo Ishiguro","The Remains of the Day, first 50 pages",40,"Read the opening section — Stevens's diary of his motoring trip. He keeps digressing into his definition of a 'great butler' and you slowly realize every anecdote hides some humiliation he can't admit. Notice his prose — formal, precise, unable to name emotions but somehow making you feel them anyway.",["British","Fiction","Historical","20th Century"],"the-remains-of-the-day"),

mk("BOOKS","Book","Pachinko (2017)","Min Jin Lee's multi-generational saga of a Korean family in Japan from 1910 to the 1980s. Koreans in Japan — Zainichi — were treated as permanent foreigners even after generations. The novel was rejected by every major publisher in New York before it became a National Book Award finalist and a bestseller.","Min Jin Lee","Pachinko, Book I: Gohyang/Hometown 1910-1933",45,"Read Book I. Sunja, a teenager in a Korean fishing village, becomes pregnant by a married yakuza and is saved by a minister who offers to marry her and take her to Japan. Notice how Lee embeds the history of colonization in the smallest domestic moments — a bowl of rice, a boarding house, a pachinko parlor.",["Korean-American","Historical Fiction","Contemporary","21st Century"],"pachinko"),
]
added += append_batch("books.json", books_batch, "BOOKS")

print(f"\nTotal added: {added}")
print(f"Authors: {count('authors.json')} | Books: {count('books.json')}")

# ======================
# BATCH 2 — Authors (35)
# ======================
print("\n--- Batch 2 ---")
a2 = [
mk("AUTHORS","Author","Chimamanda Ngozi Adichie","Nigerian writer whose TED talk 'We Should All Be Feminists' was sampled by Beyonce on 'Flawless.' Her novel 'Half of a Yellow Sun' won the Women's Prize and is about the Biafran War — a war her grandfathers fought on opposite sides.","","Half of a Yellow Sun, Part One",35,"Read Part One. The novel opens in the early 1960s with a houseboy named Ugwu — through his eyes you see the buildup to war as domestic tension. Adichie wrote this because she grew up surrounded by Biafran veterans but never saw their story in fiction. Notice how the privileged dinner conversations slowly tip toward catastrophe.",["Nigerian","Fiction","Historical","21st Century"],"chimamanda-adichie"),

mk("AUTHORS","Author","Jorge Luis Borges","Argentine librarian who went blind while director of the National Library and wrote stories so dense they invented literary theory before theory existed. His story 'The Library of Babel' imagines the universe as a library containing every possible book — and the librarians who search it forever.","","Ficciones, any 3 stories",28,"Read three stories: 'The Library of Babel,' 'Pierre Menard,' and 'Tlon, Uqbar.' Borges writes philosophy disguised as detective stories. 'Pierre Menard' is a review of a book that doesn't exist — a man who tries to write 'Don Quixote' word-for-word in the 20th century. Notice the footnotes are fake but the scholarship is real.",["Argentine","Fiction","Magical Realism","20th Century"],"jorge-luis-borges"),

mk("AUTHORS","Author","Toni Morrison","The first Black woman to win the Nobel Prize in Literature (1993). She wrote 'Beloved' based on the true story of Margaret Garner, an enslaved woman who killed her own daughter rather than let her be returned to slavery. Morrison started writing at 39 and worked as an editor at Random House championing Black authors.","","Beloved, first 50 pages",40,"Read the opening. A house at 124 Bluestone Road is haunted by a baby ghost — '124 was spiteful.' Morrison wrote the novel in fragments because trauma doesn't remember in straight lines. She never explains the haunting; she lets you feel it. Notice the shifting tense — past and present blur because the past isn't past.",["American","Fiction","Historical","20th Century"],"toni-morrison"),

mk("AUTHORS","Author","Haruki Murakami","Japanese novelist who was watching a baseball game in 1978 when an American player hit a double and Murakami suddenly knew he could write a novel. He bought paper on the way home. His books mix cats, jazz, parallel worlds, and women who disappear. He ran a jazz bar in Tokyo before becoming a writer.","","Kafka on the Shore, first 3 chapters",30,"Read the opening chapters. Two narratives alternate: Kafka Tamura, a 15-year-old runaway, and Nakata, an old man who can talk to cats. Notice how Murakami describes surreal events with the same flat tone he uses for making spaghetti — the magic never announces itself. The cats are the most normal people in the book.",["Japanese","Fiction","Magical Realism","Contemporary"],"haruki-murakami"),

mk("AUTHORS","Author","Clarice Lispector","Brazilian writer born in Ukraine who fled pogroms as an infant. Her novels are more interior monologue than plot — 'The Hour of the Star' (1977) follows a poor girl from the northeast of Brazil who eats hot dogs and dreams of being a movie star. Lispector died the year it was published, at 56.","","The Hour of the Star, the whole novella",42,"Read the whole novella — it's only 96 pages. A male narrator invents Macabea, a typist so poor and plain she's almost invisible. The narrator keeps interrupting to tell you he doesn't know how to write this. Notice how Lispector makes you question who has the right to tell whose story — the frame narrator is the real subject.",["Brazilian","Fiction","Modernist","20th Century"],"clarice-lispector"),

mk("AUTHORS","Author","Ngugi wa Thiong'o","Kenyan writer who was imprisoned for a year without trial (1977) for a play performed in his native Gikuyu — the government saw a vernacular play as seditious. In prison he wrote his first novel in Gikuyu on toilet paper. He later declared he would never write fiction in English again.","","A Grain of Wheat, the first section",35,"Read the opening section. Set on the eve of Kenya's independence (1963), the novel follows several villagers, each hiding a secret about the Mau Mau rebellion. Ngugi wrote it in English before his Gikuyu-only vow, but it already wrestles with what colonialism did to language. Notice how every character is lying about something heroic.",["Kenyan","Fiction","Postcolonial","20th Century"],"ngugi-wa-thiongo"),

mk("AUTHORS","Author","Ursula K. Le Guin","Wrote 'The Left Hand of Darkness' in 1969 — a sci-fi novel that treats gender as a social construct decades before that was mainstream. Her parents were anthropologists, and her fiction always reads like ethnography of imaginary cultures. Her Earthsea books proved fantasy could be literary before anyone else tried.","","A Wizard of Earthsea, first 3 chapters",25,"Read the opening. Ged, a boy with a gift for magic, goes to wizard school and in a fit of pride summons a shadow monster. The rest of the novel is the chase — but the shadow is hunting him too. Notice Le Guin's magic isn't a set of rules but a moral weight: every spell has a cost, and names are power.",["American","Fantasy","Science Fiction","20th Century"],"ursula-le-guin"),

mk("AUTHORS","Author","Naguib Mahfouz","The only Arabic-language writer to win the Nobel Prize (1988). His Cairo Trilogy follows a Cairene family from WWI to the 1950s — three generations, three novels, every page set in the same neighborhood. He was stabbed in the neck by an Islamist extremist in 1994 for his secular views but survived.","","Palace Walk, first section",35,"Read the opening of Palace Walk — the first novel of the Cairo Trilogy. The patriarch al-Sayyid Ahmad is a tyrant at home and a charmer in the streets. Mahfouz builds an entire world in one Cairene alley. Notice how the mother, Amina, is the novel's real conscience — watching from the balcony she's never allowed to leave.",["Egyptian","Fiction","Historical","20th Century"],"naguib-mahfouz"),

mk("AUTHORS","Author","Cormac McCarthy","American novelist who wrote 'The Road' on a typewriter and gave his Pulitzer Prize money ($10,000) to a Mexican orphanage. He lived in motels for years and never gave a real interview until Oprah in 2007. His novel 'Blood Meridian' is considered by many critics the greatest American novel since Moby-Dick.","","The Road, first 30 pages",25,"Read the opening. A father and son walk through a dead world pushing a shopping cart. McCarthy strips every sentence to its bones — no quotation marks, no chapter numbers, no character names beyond 'the man' and 'the boy.' Notice how the boy is the only moral compass in a world where kindness costs everything.",["American","Fiction","Post-Apocalyptic","21st Century"],"cormac-mccarthy"),

mk("AUTHORS","Author","Banana Yoshimoto","Japanese writer who debuted with 'Kitchen' in 1988 — a novella about grief and cooking. It sold 2 million copies in Japan and started a phenomenon called 'Bananamania.' The novella opens with the line 'The place I like best in this world is the kitchen' and grief is processed through food, not tears.","","Kitchen, the whole novella",40,"Read Kitchen — it's short. A young woman named Mikage, orphaned, finds comfort sleeping next to a refrigerator. She moves in with a young man and his transgender mother. Notice how Yoshimoto's prose is translucent — everything is lit from within, and death never makes the page feel dark. This is mourning as a warm room.",["Japanese","Fiction","Contemporary","20th Century"],"banana-yoshimoto"),
]
added += append_batch("authors.json", a2, "AUTHORS")

# ======================
# BATCH 2 — Books (35)
# ======================
b2 = [
mk("BOOKS","Book","Beloved (1987)","Toni Morrison's novel based on the true story of Margaret Garner — a woman who killed her child rather than see her enslaved. The ghost of the baby haunts 124 Bluestone Road, and then one day a young woman called Beloved walks out of the water. Morrison used newspaper clippings from 1856 as her starting point. Won the Pulitzer.","Toni Morrison","Beloved, Part One",42,"Read Part One. The novel opens with '124 was spiteful. Full of a baby's venom.' Morrison writes in fragments because trauma doesn't narrate linearly — past and present dissolve into each other. The ghost is real, but Morrison never explains how. Notice how the prose rhythm matches the characters' breathing — it speeds up when the memories come.",["American","Historical Fiction","Gothic","20th Century"],"beloved"),

mk("BOOKS","Book","The Name of the Rose (1980)","Umberto Eco's debut novel — a murder mystery set in a 14th-century monastery where monks are being killed because of a book. Eco was a semiotics professor and the novel is secretly a textbook on medieval philosophy disguised as a thriller. The library is a labyrinth; the killer's motive involves Aristotle's lost treatise on comedy.","Umberto Eco","The Name of the Rose, First Day",45,"Read 'First Day.' The Franciscan friar William of Baskerville arrives at the abbey and immediately starts deducing things Sherlock Holmes-style — he reconstructs a lost horse from hoofprints. A monk is dead in the scriptorium. Notice how Eco makes the monastery feel like a university campus: jealousies, forbidden books, scholars who'd kill for knowledge.",["Italian","Historical Fiction","Mystery","20th Century"],"the-name-of-the-rose"),

mk("BOOKS","Book","Never Let Me Go (2005)","Kazuo Ishiguro's dystopia that hides its dystopia — the narrator, Kathy H., is a carer at a boarding school, and the horror of what the school is for only dawns on you slowly. Ishiguro said he wanted to write about mortality, and cloning was just the vehicle. The novel never uses the word 'clone.'","Kazuo Ishiguro","Never Let Me Go, Part One",35,"Read Part One. Kathy describes Hailsham, her old school, in nostalgic detail — the guardians, the art classes, the mysterious 'donations.' Something is wrong but Ishiguro makes you feel it through what Kathy doesn't say. She's a carer, but she's also a 'donor.' The word 'clone' never appears. The tragedy is that Kathy never questions her purpose.",["British","Science Fiction","Dystopian","21st Century"],"never-let-me-go"),

mk("BOOKS","Book","Things Fall Apart (1958)","Chinua Achebe wrote this novel specifically because he was tired of how Africans were portrayed in English literature — Conrad's 'Heart of Darkness' in particular. The novel follows Okonkwo, a respected Igbo warrior, as his world is dismantled by British colonialism and Christian missionaries. It's the most-read African novel in history.","Chinua Achebe","Things Fall Apart, Part One",30,"Read Part One. Achebe writes in English but the cadence is Igbo — proverbs structure the narration, and the novel feels oral even on the page. Okonkwo is a great man who beats his wives and kills his adopted son because the village demands it. Notice how Achebe makes colonialism a tragedy, not a rescue — and Okonkwo is its tragic hero.",["Nigerian","Historical Fiction","Postcolonial","20th Century"],"things-fall-apart"),

mk("BOOKS","Book","The God of Small Things (1997)","Arundhati Roy's debut novel won the Booker Prize and made her famous — then she stopped writing fiction for 20 years to become an activist. Set in Kerala, India, it's about fraternal twins Estha and Rahel and the one day in 1969 when everything fell apart. The novel was banned in parts of India for its portrayal of caste.","Arundhati Roy","The God of Small Things, first 5 chapters",38,"Read the opening chapters. Roy wrote the novel like music — words get repeated and changed, sentences loop back on themselves. The story is told out of order because memory doesn't work in order. Notice how 'the Love Laws' — rules about who can love whom — govern every character's fate. The children break one law and the novel breaks your heart.",["Indian","Fiction","Literary","20th Century"],"the-god-of-small-things"),
]
added += append_batch("books.json", b2, "BOOKS")

print(f"\nCumulative added: {added}")
print(f"Authors: {count('authors.json')} | Books: {count('books.json')}")

# ======================
# BATCH 3 — Authors (38)
# ======================
print("\n--- Batch 3 ---")
a3 = [
mk("AUTHORS","Author","Virginia Woolf","Pioneered stream-of-consciousness technique in novels like 'Mrs Dalloway' (1925), which takes place in a single day. She and her husband Leonard founded Hogarth Press — they hand-printed their first book on their dining table. Her essay 'A Room of One's Own' (1929) argued that a woman needs money and a room of her own to write fiction.","","Mrs Dalloway, first section",28,"Read the opening pages. Clarissa Dalloway walks through London buying flowers for her party. Woolf makes a single June day contain an entire life — memories of a summer at Bourton, a kiss, a choice made 30 years ago. Notice how the narration drifts between characters like a bee visiting flowers: Clarissa, then Septimus, then back.",["British","Fiction","Modernist","20th Century"],"virginia-woolf"),

mk("AUTHORS","Author","Franz Kafka","Prague-born writer who worked at an insurance company by day and wrote at night. He made his friend Max Brod promise to burn all his manuscripts after his death — Brod published them instead. His stories about bureaucracies crushing individuals gave us the word 'Kafkaesque.' He died of tuberculosis at 40, mostly unpublished.","","The Metamorphosis, the whole novella",25,"Read the whole novella — about 60 pages. Gregor Samsa wakes up as a giant insect. His first thought: how will I get to work? Kafka never explains the transformation; the horror is the family's reaction, not the bug. Notice the deadpan tone — Kafka tells the impossible like a police report. Gregor's humanity fades as his family's indifference grows.",["Czech","Fiction","Modernist","20th Century"],"franz-kafka"),

mk("AUTHORS","Author","Gabriel Garcia Marquez","Colombian novelist who won the Nobel Prize in 1982. He was working as a journalist in Mexico City when the opening line of 'One Hundred Years of Solitude' came to him while driving — he turned the car around and started writing that night. Sold 8,000 copies in the first week and has now sold over 50 million.","","One Hundred Years of Solitude, first 3 chapters",35,"Read the opening. 'Many years later, as he faced the firing squad, Colonel Aureliano Buendia was to remember that distant afternoon when his father took him to discover ice.' In three sentences Marquez collapses time. The novel invents Macondo, a town so new that things don't have names yet. Notice the deadpan magic — a woman ascending to heaven while folding sheets is described with the same tone as the weather.",["Colombian","Fiction","Magical Realism","20th Century"],"gabriel-garcia-marquez"),

mk("AUTHORS","Author","Milan Kundera","Czech-French novelist who wrote 'The Unbearable Lightness of Being' (1984) — a novel where the narrator is also a philosopher, interrupting the story to explain Nietzsche's concept of eternal return. He was exiled from Czechoslovakia in 1975 for his role in the Prague Spring. His Czech citizenship was revoked; France adopted him.","","The Unbearable Lightness of Being, Part One",30,"Read Part One. The narrator introduces Tomas, a surgeon, and Tereza, a waitress, and then starts philosophizing about lightness vs. weight. Kundera treats his characters like ideas — he'll describe them, then analyze what they mean. Notice how the 1968 Soviet invasion of Prague becomes a backdrop for a love story about whether commitment is heaviness or meaning.",["Czech","Fiction","Philosophical","20th Century"],"milan-kundera"),

mk("AUTHORS","Author","Zadie Smith","British novelist whose debut 'White Teeth' (2000) earned her a six-figure advance while she was still at Cambridge. The novel was auctioned based on 80 pages. It spans three families in multicultural London: Bangladeshi, Jamaican, and Jewish. Smith was 24 when it was published. She later said she wishes she could rewrite the ending.","","White Teeth, first 5 chapters",40,"Read the opening chapters. Archie Jones tries to gas himself in his car on New Year's Day 1975 but is saved by a halal butcher. Smith writes London's diversity as joy, not conflict — her sentences are elastic, bouncing between street slang and Latinate precision. Notice the novel's obsession with teeth: as roots, as history, as objects that last longer than we do.",["British","Fiction","Contemporary","21st Century"],"zadie-smith"),

mk("AUTHORS","Author","Leo Tolstoy","Russian novelist who wrote 'War and Peace' (1869) — one of the longest novels ever — while having 13 children. He wrestled it for six years and his wife Sonya hand-copied the manuscript seven times (about 3,000 pages each time). He renounced his wealth at 50, gave away his copyrights, and died at a train station after leaving home at 82.","","War and Peace, Book One, Part One",45,"Read the opening. Anna Pavlovna's soirée in 1805 St. Petersburg. Napoleon is threatening Russia; the aristocracy gossips in French. Pierre Bezukhov, the illegitimate son of a count, blunders into the room and starts arguing for Napoleon. Notice how Tolstoy introduces 20 characters in 30 pages — each one distinct, each one convinced they're the protagonist of history.",["Russian","Fiction","Historical","19th Century"],"leo-tolstoy"),

mk("AUTHORS","Author","Jane Austen","Published all her novels anonymously — the title page of 'Pride and Prejudice' (1813) says only 'By the Author of Sense and Sensibility.' She wrote on small slips of paper that could be hidden when visitors came, because writing wasn't considered ladylike. Her novels were modestly successful in her lifetime; she died at 41, never knowing her posthumous fame.","","Pride and Prejudice, first 10 chapters",35,"Read the first ten chapters. 'It is a truth universally acknowledged, that a single man in possession of a good fortune must be in want of a wife.' That opening sentence is ironic — Austen's narrator is always winking. Notice the free indirect discourse: the narrator speaks in Elizabeth Bennet's voice without attribution. You know Elizabeth's thoughts because the grammar itself changes.",["British","Fiction","Romance","19th Century"],"jane-austen"),

mk("AUTHORS","Author","Fyodor Dostoevsky","Sentenced to death by firing squad in 1849 for reading banned books — at the last second a messenger arrived with a reprieve from the Tsar, commuting his sentence to Siberian exile. The mock execution broke him. He became one of the greatest psychological novelists, writing about guilt, God, and the darkest corners of human consciousness.","","Crime and Punishment, Part One",40,"Read Part One. Raskolnikov, a destitute student in St. Petersburg, plans and executes a murder. Dostoevsky wrote the novel as he was gambling away his advance — the urgency is on every page. Raskolnikov doesn't feel guilt; he feels fever. Notice how the city itself is a character: the stifling rooms, the yellow walls, the crowds that see everything and nothing.",["Russian","Fiction","Psychological","19th Century"],"fyodor-dostoevsky"),

mk("AUTHORS","Author","Kurt Vonnegut","American satirist whose novel 'Slaughterhouse-Five' (1969) is based on his experience as a POW who survived the firebombing of Dresden — he witnessed the destruction from a meat locker underground. He called the book 'a failure' on the first page. The aliens in the novel — Tralfamadorians — see all time at once, so death is just 'so it goes.'","","Slaughterhouse-Five, chapters 1-2",25,"Read the first two chapters. Vonnegut introduces himself as a character struggling to write about Dresden. Billy Pilgrim has 'come unstuck in time.' Notice the refrain 'So it goes' — it appears after every mention of death. Vonnegut uses it 106 times. The novel is anti-war but refuses to dramatize: war is never glorious, just absurd and sad.",["American","Fiction","Satire","20th Century"],"kurt-vonnegut"),

mk("AUTHORS","Author","Murasaki Shikibu","Japanese lady-in-waiting who wrote 'The Tale of Genji' around the year 1008 — arguably the world's first novel and first psychological novel, centuries before anything comparable appeared in the West. She wrote it chapter by chapter, passing pages around the court. The novel is over 1,300 pages and follows the romantic life of Prince Genji.","","The Tale of Genji, first 3 chapters",40,"Read the opening chapters. Genji's mother dies when he's young; he spends the rest of the novel seeking her in other women. Murasaki writes court life in exquisite detail — poetry contests, robe layering rituals, the precise color of mourning — but beneath the beauty is loneliness. Notice how characters rarely speak directly; feelings travel through poems and proxies.",["Japanese","Fiction","Classical","11th Century"],"murasaki-shikibu"),

mk("AUTHORS","Author","Chinua Achebe","Nigerian novelist called 'the father of African literature.' His debut 'Things Fall Apart' (1958) has sold over 20 million copies and been translated into 57 languages. He wrote it because he was tired of how Conrad and others portrayed Africa. He later became a professor at Brown University and mentored a generation of African writers.","","Arrow of God, Part One",35,"Read Part One. Ezeulu, the chief priest of Ulu, is caught between his Igbo traditions and the British colonial administration. Unlike Okonkwo in Things Fall Apart, Ezeulu is intellectual — his tragedy is that his strategic thinking backfires. Achebe shows colonialism isn't just violence; it's a system that traps even the wise. Proverbs structure the prose like pillars.",["Nigerian","Fiction","Postcolonial","20th Century"],"chinua-achebe"),

mk("AUTHORS","Author","Emily Dickinson","Wrote nearly 1,800 poems but published fewer than a dozen in her lifetime — and those were heavily edited. After her death, her sister Lavinia discovered a locked chest containing hundreds of poems sewn into little booklets called fascicles. Dickinson mostly wore white, rarely left her Amherst house after her 30s, and wrote poems on envelopes and scraps of paper.","","Selected Poems, the first 15 poems",20,"Read the first 15 poems in any edition. Dickinson's punctuation is the mystery: she uses dashes where you expect commas, periods, or nothing. Her poems are short — often four stanzas — but each one telescopes from a domestic image (a funeral in the brain, a loaded gun, a narrow fellow in the grass) to cosmic questions. Read them aloud; the dashes are breaths.",["American","Poetry","19th Century"],"emily-dickinson"),

mk("AUTHORS","Author","Albert Camus","French-Algerian philosopher and novelist who won the Nobel Prize in 1957 at age 44. His novel 'The Stranger' (1942) opens with 'Mother died today. Or maybe yesterday, I don't know.' Camus called his philosophy 'absurdism' — the world is meaningless, and we must create meaning anyway. He died in a car crash at 46 with an unused train ticket in his pocket.","","The Stranger, Part One",22,"Read Part One. Meursault's mother dies; he shows no emotion. He goes to the beach; he kills a man 'because of the sun.' The novel is written in a flat, declarative style called 'white writing' — no metaphors, no interiority. Notice how the trial in Part Two judges Meursault not for murder but for not crying at his mother's funeral. The sun is the real culprit.",["French","Fiction","Philosophical","20th Century"],"albert-camus"),

mk("AUTHORS","Author","Tayeb Salih","Sudanese writer whose novel 'Season of Migration to the North' (1966) is considered the most important Arabic novel of the 20th century. It reverses Conrad's 'Heart of Darkness' — a Sudanese man goes to England, and the 'darkness' he finds is Western civilization. The Arab Literary Academy voted it the greatest Arabic novel ever written.","","Season of Migration to the North, the whole novel",50,"Read the whole novel — it's under 200 pages. Two men: the narrator, who studied in England and returned to Sudan, and Mustafa Sa'eed, a brilliant Sudanese man who seduced English women as revenge for colonialism. The novel unfolds as a conversation, then a mystery. Notice the Nile — it's always there, timeless, while the characters drown in history.",["Sudanese","Fiction","Postcolonial","20th Century"],"tayeb-salih"),

mk("AUTHORS","Author","Margaret Atwood","Canadian novelist, poet, and essayist who has published over 50 books. Her Handmaid's Tale (1985) was written in West Berlin during the Cold War, and every atrocity in the novel was based on something that already happened somewhere in history. She writes on Twitter with a dry wit and invented the LongPen — a remote book-signing robot.","","Oryx and Crake, first section",30,"Read the opening section. Snowman, possibly the last human, sleeps in a tree and talks to himself. The world has ended, and his best friend Crake may have ended it. Atwood builds a biotech dystopia piece by piece — gene-spliced animals, gated corporate compounds, a game called Extinctathon. Notice how the pre-apocalypse world feels just slightly worse than ours.",["Canadian","Fiction","Dystopian","21st Century"],"margaret-atwood"),

mk("AUTHORS","Author","Roberto Bolaño","Chilean novelist who died at 50 in 2003, just as his masterpiece '2666' was gaining global attention. He spent his youth as a vagabond poet in Mexico and Spain, once calling poetry 'braver than anyone.' His novel 'The Savage Detectives' (1998) follows a group of poets searching for a vanished writer in the Sonoran desert.","","The Savage Detectives, first section",30,"Read the first section — Juan García Madero's diary, 1975. He's 17, he joins a gang of visceral realist poets in Mexico City, and he's having sex for the first time. Bolaño writes youth as a fever: the poetry, the poverty, the conviction that literature is worth dying for. The novel's structure fractures after Part One — the diary gives way to a chorus of 50+ narrators.",["Chilean","Fiction","Contemporary","21st Century"],"roberto-bolano"),

mk("AUTHORS","Author","Doris Lessing","British-Zimbabwean novelist who won the Nobel Prize in 2007 — the oldest recipient at 88. Her novel 'The Golden Notebook' (1962) was called 'the Bible of the women's movement' though she disliked that label. She grew up in Southern Rhodesia (now Zimbabwe) and her African stories are shot through with the violence and beauty of the veld.","","The Golden Notebook, the opening 'Free Women' section",40,"Read the opening section. Anna Wulf, a writer with writer's block, keeps four notebooks — black, red, yellow, blue — for different parts of her life. The novel itself is structured like those notebooks, interleaving Anna's 'real' life with her fictionalized versions. Lessing wrote it as a formal experiment to show how someone's mind fractures under pressure.",["British","Fiction","Feminist","20th Century"],"doris-lessing"),

mk("AUTHORS","Author","John Steinbeck","American novelist who drove across the country to research 'The Grapes of Wrath' (1939) — he lived in migrant camps, ate what they ate, and filed reports. When the novel was published, some counties in California burned it. Steinbeck won the Nobel Prize in 1962. His dog ate the first draft of 'Of Mice and Men,' and he had to rewrite it from memory.","","East of Eden, chapters 1-5",40,"Read the opening chapters. Steinbeck calls it 'the only book I have ever written' — all his others were practice. Set in the Salinas Valley, it retells the Cain and Abel story across two generations. The first chapter is a pure description of the valley through seasons — it reads like the Old Testament. Notice the Hebrew word 'timshel' (thou mayest) — it becomes the novel's thesis about free will.",["American","Fiction","Literary","20th Century"],"john-steinbeck"),

mk("AUTHORS","Author","George Orwell","British writer born Eric Blair who fought in the Spanish Civil War — a sniper's bullet went through his throat. That experience radicalized him against totalitarianism. He wrote '1984' while dying of tuberculosis on the Scottish island of Jura. The novel's title was originally 'The Last Man in Europe,' and he finished it weeks before his death at 46.","","Homage to Catalonia, first half",35,"Read the first half — Orwell's memoir of fighting fascism in Spain. He arrives idealistic, fights in the trenches, gets shot in the neck ('the whole experience of being hit by a bullet is very interesting'), and watches the left eat itself in the Barcelona street fighting of May 1937. This is where Animal Farm and 1984 were born — not in dystopia but in firsthand betrayal.",["British","Fiction","Political","20th Century"],"george-orwell"),

mk("AUTHORS","Author","Han Kang","South Korean writer whose novel 'The Vegetarian' (2007) won the International Booker Prize in 2016. It's told in three parts about a woman who stops eating meat after a dream. Her family's reaction escalates to force-feeding and institutionalization. Han writes about bodies, violence, and refusal with unnerving stillness.","","The Vegetarian, Part One: The Vegetarian",28,"Read Part One, narrated by the husband — a dull man whose wife Yeong-hye stops eating meat after a dream of blood. He's not concerned for her; he's annoyed the dinner parties are awkward. Notice how Han uses the husband's banality as the real horror: his wife is in crisis and all he can think about is his professional standing. The spare prose leaves room for the unsaid.",["South Korean","Fiction","Contemporary","21st Century"],"han-kang"),

mk("AUTHORS","Author","Herman Melville","American novelist who was hugely popular for his early sea adventures, then wrote 'Moby-Dick' (1851) and his career collapsed — the book sold 3,715 copies in his lifetime. At the time of his death, he was remembered — if at all — as 'the man who lived among the cannibals.' The 20th century rediscovered him as one of America's greatest writers.","","Bartleby the Scrivener, the whole story",22,"Read the whole story — about 40 pages. A Wall Street lawyer hires Bartleby, a copyist who one day responds to a request with 'I would prefer not to.' That phrase becomes his only response to everything. Melville never explains Bartleby; he's a blank wall. Notice the lawyer-narrator's growing sympathy and frustration — Bartleby's passive resistance is unanswerable. It's a comedy until it isn't.",["American","Fiction","19th Century"],"herman-melville"),

mk("AUTHORS","Author","Anton Chekhov","Russian doctor and writer who practiced medicine while writing — he once said 'medicine is my lawful wife; literature is my mistress.' He revolutionized the short story by removing the moral. His plays — 'The Seagull,' 'Uncle Vanya,' 'The Cherry Orchard' — were initially failures, then transformed theatre by insisting that life on stage should feel like life off stage.","","The Lady with the Little Dog, plus 2 other stories",25,"Read 'The Lady with the Little Dog' and two others. Chekhov's stories don't end; they stop. His characters are usually decent people realizing their lives have been wasted — and Chekhov never judges them. Notice the details that carry entire emotional worlds: a slice of watermelon eaten in silence, a grey fence with nails, a bit of string. Everything matters; nothing is explained.",["Russian","Fiction","Short Stories","19th Century"],"anton-chekhov"),

mk("AUTHORS","Author","Isabel Allende","Chilean-American novelist who started 'The House of the Spirits' (1982) as a letter to her dying 99-year-old grandfather. She was living in exile in Venezuela after Pinochet's coup killed her cousin Salvador Allende. The novel became a bestseller and launched her career as the most widely read Latin American woman writer in the world.","","The House of the Spirits, first section",35,"Read the opening. Clara, a clairvoyant child, writes everything in notebooks called 'notebooks that bear witness to life.' The novel spans four generations of the Trueba family in an unnamed Latin American country. Allende writes magic as a family trait — Clara moves salt shakers with her mind. Notice the blend of domesticity and political violence: a wedding reception and a military coup share equal weight.",["Chilean","Fiction","Magical Realism","20th Century"],"isabel-allende"),

mk("AUTHORS","Author","Yukio Mishima","Japanese novelist, playwright, and bodybuilder who wrote 40 novels before attempting a coup at a military base in 1970. After his speech was mocked by soldiers, he committed ritual suicide (seppuku) on the general's balcony. His 'Sea of Fertility' tetralogy is a meditation on reincarnation across 20th-century Japan. His death shocked the world.","","Spring Snow, first section",38,"Read the opening of Spring Snow — the first novel of the Sea of Fertility tetralogy. 1912 Tokyo: Kiyoaki Matsugae, a young aristocrat, falls in love with Satoko, the woman he's too proud to pursue until she's engaged to a prince. Mishima's prose is impossibly beautiful — cherry blossoms, kimonos, the dying elegance of the old Japan. Notice the cruelty beneath the beauty.",["Japanese","Fiction","Modernist","20th Century"],"yukio-mishima"),

mk("AUTHORS","Author","J.M. Coetzee","South African novelist who won the Booker Prize twice and the Nobel Prize in 2003. He writes novels so spare they feel carved — his prose has no fat. 'Disgrace' (1999) follows a Cape Town professor after a scandal, examining race, power, and violence in post-apartheid South Africa. Coetzee is famously private: he didn't collect either Booker Prize in person.","","Disgrace, the whole novel",48,"Read the whole novel — it's relatively short. David Lurie, a 52-year-old professor, loses everything after an affair with a student and retreats to his daughter's farm in the Eastern Cape. Violence arrives. Coetzee writes in present tense with no quotation marks, making every sentence feel like a verdict. Notice the dogs — Lurie volunteers at an animal shelter, and they become the novel's moral center.",["South African","Fiction","Literary","21st Century"],"jm-coetzee"),

mk("AUTHORS","Author","Salman Rushdie","British-Indian novelist whose 1988 novel 'The Satanic Verses' led to a fatwa calling for his death. He lived under police protection for nine years, moving safe houses every few days. His novel 'Midnight's Children' (1981) won the Booker Prize and was named the Best of the Bookers twice — at the 25th and 40th anniversaries of the prize.","","Midnight's Children, Book One",40,"Read Book One. Saleem Sinai, born at the stroke of midnight on August 15, 1947 — the exact moment of India's independence — narrates his extraordinary life. All children born in that first hour have magical powers, and Saleem can enter their minds. Notice the narration is a chutney of history and myth: the personal and national collapse into one another. Rushdie's prose is maximalist joy.",["British-Indian","Fiction","Postcolonial","20th Century"],"salman-rushdie"),

mk("AUTHORS","Author","Louise Erdrich","Native American (Ojibwe) novelist who runs Birchbark Books, an independent bookstore in Minneapolis. Her novel 'The Round House' (2012) won the National Book Award and is about a 13-year-old boy seeking justice after his mother is attacked on a reservation — where tribal and federal law create a jurisdictional maze.","","The Round House, first half",40,"Read the first half. Joe's mother is attacked and won't speak about it. Joe and his friends start their own investigation, biking around the reservation. Erdrich embeds the legal injustice in the details — the crime happened in a round house (a sacred space) near the reservation boundary, and jurisdiction depends on whose land the rock was sitting on. Notice how humor coexists with horror.",["American","Fiction","Native American","21st Century"],"louise-erdrich"),

mk("AUTHORS","Author","Wole Soyinka","Nigerian playwright and poet who won the Nobel Prize in 1986 — the first African laureate. He was imprisoned for 22 months during the Nigerian Civil War (1967-69), mostly in solitary confinement, for attempting to broker peace. He wrote poems on toilet paper and hid them in his underwear. His prison memoir 'The Man Died' was published in 1972.","","Death and the King's Horseman, the whole play",45,"Read the whole play — it's based on a real event in 1946 colonial Nigeria. The king's horseman must ritually commit suicide to accompany his king to the afterlife, but the British colonial officer intervenes. Soyinka says it's not about colonial clash but about the cosmic duty the horseman is failing. Notice the Yoruba poetry woven through the English — the play moves on two planes at once.",["Nigerian","Drama","Postcolonial","20th Century"],"wole-soyinka"),

mk("AUTHORS","Author","Ocean Vuong","Vietnamese-American poet and novelist who was born in Saigon, raised in Hartford, Connecticut by his mother and grandmother — both illiterate. His debut novel 'On Earth We're Briefly Gorgeous' (2019) is a letter from a son to a mother who can't read. He was the first in his family to learn to read, at age 11.","","On Earth We're Briefly Gorgeous, first half",35,"Read the first half. The narrator, Little Dog, writes to his mother Rose, a Vietnamese nail salon worker who can't read English. The novel moves between the Vietnam War, the nail salon, and a doomed first love with a white boy in Connecticut. Vuong writes prose like poetry — every sentence is chiseled. Notice the recurring image of the monarch butterfly migration: fragile, beautiful, inevitable.",["Vietnamese-American","Fiction","Contemporary","21st Century"],"ocean-vuong"),

mk("AUTHORS","Author","Orhan Pamuk","Turkish novelist who won the Nobel Prize in 2006. His novel 'My Name Is Red' (1998) is a murder mystery set among 16th-century Ottoman miniature painters — and includes chapters narrated by a corpse, a coin, and the color red. He was charged with 'insulting Turkishness' in 2005 for mentioning the Armenian genocide; the charges were later dropped.","","My Name Is Red, first 8 chapters",40,"Read the first eight chapters. Each chapter has a different narrator: a corpse, a dog, a tree, a murderer, the color red. Pamuk uses this polyphonic structure to explore the clash between Islamic miniature painting and Western perspective — the murder is about art. Notice how magical the object-narrators feel: the coin's chapter is a miniature economic history of Istanbul.",["Turkish","Fiction","Historical","21st Century"],"orhan-pamuk"),

mk("AUTHORS","Author","E.B. White","American essayist and children's author who wrote 'Charlotte's Web' (1952) in a boathouse in Maine. He also co-wrote 'The Elements of Style' — the most famous English writing guide — with his college professor Strunk. He once drove a Model T across the country and wrote essays about it. His spider heroine Charlotte was based on a real spider in his barn.","","Charlotte's Web, the whole book",40,"Read the whole book — it's about 180 pages. Wilbur the pig is saved from slaughter by Charlotte the spider, who weaves words into her web: 'Some Pig,' 'Terrific,' 'Radiant.' White wrote it after watching a spider spin an egg sac in his barn. Notice how death is never lied about — Charlotte dies at the county fair, and her children float away on silk threads. The book teaches grief to children without patronizing them.",["American","Children's Literature","20th Century"],"eb-white"),

mk("AUTHORS","Author","Bessie Head","Born in South Africa to a white mother and black father during apartheid — her mother was institutionalized, and Bessie was raised in foster care. She fled to Botswana as a refugee and wrote novels about exile, mental illness, and village life. 'A Question of Power' (1973) is a semi-autobiographical novel about a woman's psychotic breakdown.","","When Rain Clouds Gather, first half",38,"Read the first half. Makhaya, a South African refugee, arrives in a Botswanan village and meets Gilbert, an English agriculturalist trying to teach modern farming. The village is dying of drought and tradition. Head writes about rural Africa with love that never romanticizes — the village has beauty and cruelty in equal measure. Notice how exile is the central experience: Makhaya can never go home.",["Botswanan","Fiction","Postcolonial","20th Century"],"bessie-head"),

mk("AUTHORS","Author","Miguel de Cervantes","Spanish writer whose 'Don Quixote' (1605, 1615) is considered the first modern novel. He published Part One at 58 after a life of extraordinary failure: he was wounded at the Battle of Lepanto (losing use of his left hand), captured by pirates and enslaved in Algiers for five years, imprisoned for debt, and excommunicated twice.","","Don Quixote, chapters 1-10",42,"Read the first ten chapters. Alonso Quijano reads so many chivalric romances that he loses his mind and reinvents himself as Don Quixote, knight-errant. His first adventure: he 'frees' a boy being whipped by a farmer, rides away feeling heroic, and the farmer beats the boy twice as hard. Cervantes invents metafiction 400 years early — the characters in Part Two have read Part One and know they're famous.",["Spanish","Fiction","Classical","17th Century"],"miguel-de-cervantes"),

mk("AUTHORS","Author","Jamaica Kincaid","Antiguan-American writer whose novel 'Annie John' (1985) follows a girl's coming-of-age on Antigua — but the real love story is between mother and daughter, whose relationship curdles into something dark. Kincaid was sent to America at 17 to work as an au pair and never went home. Her prose is incantatory — it builds rhythm until the meaning hits.","","A Small Place, the whole essay",28,"Read the whole essay — it's about 80 pages. Kincaid addresses the reader as a tourist arriving in Antigua. She shows you the beauty, then the sewage system, then the corruption, then the history of slavery, then the library damaged by an earthquake and never repaired. Notice the second-person address: 'You are a tourist' — Kincaid makes you complicit, then educates you, then refuses to forgive you.",["Antiguan-American","Fiction","Postcolonial","20th Century"],"jamaica-kincaid"),

mk("AUTHORS","Author","F. Scott Fitzgerald","American novelist who wrote 'The Great Gatsby' (1925) in the south of France while his wife Zelda was having an affair with a French aviator. The novel sold poorly in his lifetime — 20,000 copies in the first year. Fitzgerald died at 44 believing himself a failure. During WWII, the U.S. military printed and distributed 150,000 copies to soldiers, creating its posthumous fame.","","The Great Gatsby, chapters 1-3",28,"Read the first three chapters. Nick Carraway moves to West Egg, attends his neighbor Gatsby's party, and meets the man himself: a smile 'with a quality of eternal reassurance in it.' Fitzgerald's style is distilled romance — every sentence is a cocktail. Notice Nick as narrator: he claims to be 'inclined to reserve all judgments' and then judges everyone. The green light at the end of Daisy's dock: it's only mentioned twice and it means everything.",["American","Fiction","Jazz Age","20th Century"],"f-scott-fitzgerald"),

mk("AUTHORS","Author","Patricia Lockwood","American poet and memoirist who became famous on Twitter for surrealist one-liners ('What's the deal with the back of the knee?') before writing 'Priestdaddy' (2017), a memoir about growing up with a father who is a married Catholic priest. Her novel 'No One Is Talking About This' (2021) was shortlisted for the Booker Prize and is narrated in the voice of the internet.","","No One Is Talking About This, the first half",30,"Read the first half. An unnamed woman famous for a viral tweet ('Can a dog be twins?') scrolls through the 'portal' — the internet — in fragments that feel like scrolling. Then her sister's baby is born with a fatal genetic condition, and the novel shifts registers completely. Lockwood's prose is the internet's id made conscious: profound and stupid in the same sentence. Notice how the portal voice cracks when real grief enters.",["American","Fiction","Contemporary","21st Century"],"patricia-lockwood"),

mk("AUTHORS","Author","Jhumpa Lahiri","American writer born to Bengali immigrants who won the Pulitzer Prize for her debut story collection 'Interpreter of Maladies' (1999) — the first time a debut collection had won the Pulitzer. In 2012 she moved to Rome, learned Italian, and started writing exclusively in Italian, later translating herself back into English.","","Interpreter of Maladies, first 3 stories",35,"Read the first three stories: 'A Temporary Matter,' 'When Mr. Pirzada Came to Dine,' and 'Interpreter of Maladies.' Husbands and wives drift apart during scheduled power outages. A girl watches her father's friend from Dacca during the 1971 Bangladesh war. A tour guide reveals his other life. Lahiri writes emotional restraint so precise it's devastating — every story has a silence that's louder than the dialogue.",["Indian-American","Fiction","Short Stories","20th Century"],"jhumpa-lahiri"),

mk("AUTHORS","Author","R.F. Kuang","Chinese-American novelist who wrote 'Babel' (2022) — a dark academia fantasy about translation, colonialism, and the violence embedded in language — while still in her 20s. Her debut 'The Poppy War' (2018) sold to Harper Voyager when she was 21. She has a Marshall Scholarship and degrees from Cambridge and Oxford and is now at Yale Law School.","","Babel, Book I",45,"Read Book I. Robin Swift, a Chinese orphan, is brought to Oxford to study at Babel — the Royal Institute of Translation, where silver bars inscribed with words in two languages produce magical effects. The magic is powered by what's lost in translation. Kuang builds a rigorous magical system out of linguistics. Notice the footnotes: they're scholarly asides that deepen the themes of empire, language, and violence.",["Chinese-American","Fantasy","Historical","21st Century"],"rf-kuang"),
]
added += append_batch("authors.json", a3, "AUTHORS")
print(f"Cumulative added: {added} | Authors: {count('authors.json')} | Books: {count('books.json')}")

# ======================
# BATCH 3 — Books (38)
# ======================
print("\n--- Batch 3b — Books ---")
b3 = [
mk("BOOKS","Book","One Hundred Years of Solitude (1967)","Garcia Marquez's novel follows the Buendia family over seven generations in the town of Macondo. The opening line collapses past, present, and future into one sentence. Over 50 million copies sold. The novel was written over 18 months while Garcia Marquez's wife pawned their car and furniture to buy food and paper.","Gabriel Garcia Marquez","One Hundred Years of Solitude, chapters 1-5",50,"Read the first five chapters. Jose Arcadio Buendia founds Macondo, and the gypsy Melquiades arrives with magnets, telescopes, and ice. Garcia Marquez reports miracles as casually as the weather — Remedios ascends to heaven while doing laundry, a rain of yellow flowers, insomnia that erases memories. Notice the circular names: generations repeat, and time is a spiral, not a line.",["Colombian","Magical Realism","Literary","20th Century"],"one-hundred-years-of-solitude"),

mk("BOOKS","Book","Pride and Prejudice (1813)","Jane Austen's novel of manners published anonymously — the title page says only 'By the Author of Sense and Sensibility.' Elizabeth Bennet and Mr. Darcy's love story is built on mutual misjudgment. The novel sold for £110 in its first edition and has never been out of print. Austen called it 'my own darling child.'","Jane Austen","Pride and Prejudice, volume 1 (chapters 1-23)",55,"Read Volume I. Elizabeth Bennet is one of five daughters, and the estate is entailed away to Mr. Collins. Austen's narrator is ironic: 'It is a truth universally acknowledged' is a joke. Notice the free indirect discourse — the narrator slips into Elizabeth's mind without signaling, so you share her prejudice against Darcy before you know she's wrong. The proposal scene in the rain is the novel's fault line.",["British","Romance","Classic","19th Century"],"pride-and-prejudice"),

mk("BOOKS","Book","To Kill a Mockingbird (1960)","Harper Lee's only published novel for 55 years (until 'Go Set a Watchman' in 2015). It won the Pulitzer and has sold 40+ million copies. Lee based Scout's friend Dill on her childhood neighbor Truman Capote. She gave her manuscript to an editor who said it might sell 2,500 copies. She never wrote another book and refused almost all interviews.","Harper Lee","To Kill a Mockingbird, Part One",40,"Read Part One. Scout Finch narrates from childhood, looking back at one summer in Maycomb, Alabama. Boo Radley is a ghost in the house next door; the children act out his story. Notice the point of view: Scout is 6, but her narration is filtered through adult understanding. The trial of Tom Robinson is the center, but the novel earns it through the slow accumulation of small-town rhythms.",["American","Fiction","Classic","20th Century"],"to-kill-a-mockingbird"),

mk("BOOKS","Book","1984 (1949)","Orwell's final novel, written while he was dying of tuberculosis on a remote Scottish island. It was originally called 'The Last Man in Europe.' Every surveillance fear in the novel — telescreens, thought police, newspeak — was Orwell's extrapolation of wartime propaganda and Stalinist purges. The adjective 'Orwellian' entered English within a decade.","George Orwell","1984, Part One",35,"Read Part One. Winston Smith lives in Oceania where Big Brother watches. He commits his first thoughtcrime: buying a blank diary. Orwell builds the horror through details — Victory Gin that tastes like nitric acid, a torn poster that hides the alcove, the Ministry of Truth where Winston rewrites history. Notice the Appendix on Newspeak at the end of the book: the clock is still ticking.",["British","Dystopian","Political","20th Century"],"nineteen-eighty-four"),

mk("BOOKS","Book","The Master and Margarita (1967)","Mikhail Bulgakov's satirical novel written during Stalin's terror, hidden in a drawer, and published 26 years after his death. The devil visits 1930s Moscow with a talking cat. The novel alternates between Soviet mockery and the story of Pontius Pilate. When it was finally published in a censored magazine, readers photocopied the missing sections and glued them in.","Mikhail Bulgakov","The Master and Margarita, Book One",50,"Read Book One. Woland (the devil) arrives in Moscow and predicts a man's beheading by tram — which happens minutes later. His entourage includes a giant talking cat called Behemoth who drinks vodka and rides the trolley. Bulgakov wrote this knowing it would never be published in his lifetime. The satire of Soviet bureaucracy is so sharp it still draws blood. Notice Pilate's story — it's the novel within the novel.",["Russian","Satire","Fantasy","20th Century"],"the-master-and-margarita"),

mk("BOOKS","Book","The Catcher in the Rye (1951)","J.D. Salinger's novel about 72 hours in the life of Holden Caulfield after being expelled from prep school. It's been banned more than almost any other American novel — for language, for sexuality, for 'undermining authority.' Salinger became a recluse in New Hampshire and never published another book. Holden's red hunting hat has become an icon of adolescent alienation.","J.D. Salinger","The Catcher in the Rye, chapters 1-10",35,"Read the first ten chapters. Holden narrates from a sanatorium in California. He's been expelled from Pencey Prep and decided to leave early. Every sentence is in Holden's voice — sarcastic, vulnerable, obsessed with 'phonies.' Notice the red hunting hat: he wears it backwards, it makes him feel safe, and he keeps offering it to others. The ducks in Central Park: where do they go in winter? Holden keeps asking — no one answers.",["American","Fiction","Coming-of-Age","20th Century"],"the-catcher-in-the-rye"),

mk("BOOKS","Book","Anna Karenina (1878)","Tolstoy's novel about a married aristocrat who leaves her husband for a cavalry officer. The novel opens with the most famous first sentence in literature: 'Happy families are all alike; every unhappy family is unhappy in its own way.' Tolstoy originally planned a novella about an adulterous wife but kept adding — the novel now spans 800+ pages and is as much about Levin farming as Anna's tragedy.","Leo Tolstoy","Anna Karenina, Part One",48,"Read Part One. Anna arrives at the Moscow train station and meets Vronsky. A man falls under a train — bad omen. Meanwhile Levin proposes to Kitty and is rejected. Tolstoy writes consciousness like no one else: Anna's inner life is a series of sudden shifts — a feeling, then the opposite feeling. Notice how the train becomes the novel's symbol: arrival, escape, and in the end, what Anna throws herself under.",["Russian","Fiction","Classic","19th Century"],"anna-karenina"),

mk("BOOKS","Book","The Brief Wondrous Life of Oscar Wao (2007)","Junot Diaz's novel about an overweight Dominican nerd growing up in New Jersey who dreams of becoming the Dominican J.R.R. Tolkien. The novel won the Pulitzer. The footnotes — lengthy, profane, scholarly — explain Dominican history from Trujillo to the diaspora. Diaz mixes Spanglish, sci-fi references, and deep political history in every paragraph.","Junot Diaz","The Brief Wondrous Life of Oscar Wao, Part I",38,"Read Part I. The narrator Yunior tells Oscar's story — a ghetto nerd who falls in love too hard and too fast. The footnotes are as long as the page text and cover the Trujillo regime, the fuku (curse), and Dominican nerd culture. Diaz writes like he's telling you a story at 2 AM — profane, tender, full of digressions that circle back. Oscar's tragedy is that he's a romantic in a world that punishes sincerity.",["Dominican-American","Fiction","Contemporary","21st Century"],"the-brief-wondrous-life-of-oscar-wao"),

mk("BOOKS","Book","The Wind-Up Bird Chronicle (1994)","Haruki Murakami's novel about a man searching for his missing cat and then his missing wife — and falling into a well, literally and metaphorically. Set partly during the Japanese occupation of Manchuria, the novel connects personal disappearance to historical atrocity. The wind-up bird is invisible but its cry — like a spring winding — drives the plot.","Haruki Murakami","The Wind-Up Bird Chronicle, Book One: The Thieving Magpie",45,"Read Book One. Toru Okada quits his job, makes spaghetti, and receives a strange phone call from a woman who says she knows him. Then his cat disappears. Then his wife. Murakami writes the surreal with the same flat affect as the mundane — a woman who talks through a medium, a dry well, a mark on a man's cheek. Notice how WWII atrocities surface in Toru's personal story without ever feeling forced.",["Japanese","Fiction","Magical Realism","20th Century"],"the-wind-up-bird-chronicle"),

mk("BOOKS","Book","Frankenstein (1818)","Mary Shelley wrote this novel when she was 18 — on a dare. During a rainy summer at Lake Geneva, Lord Byron challenged everyone to write a ghost story. Shelley had a waking nightmare of a 'pale student of unhallowed arts' and transformed it into the first science fiction novel. Published anonymously, many assumed her husband Percy had written it.","Mary Shelley","Frankenstein, Volume I (chapters 1-8)",40,"Read Volume I. Victor Frankenstein creates life and immediately abandons it in horror. The creature learns language by spying on a family through a hole in the wall — reading Paradise Lost and Plutarch's Lives. Notice the novel's structure: a frame narrative (letters from an Arctic explorer) within a frame (Victor's confession) within the creature's own story. Who is the monster? Mary Shelley lets you decide.",["British","Gothic","Science Fiction","19th Century"],"frankenstein"),

mk("BOOKS","Book","The Color Purple (1982)","Alice Walker's novel told through letters — first Celie's letters to God, then letters between Celie and her sister Nettie. It won the Pulitzer and the National Book Award. The novel spans 40 years of Celie's life in rural Georgia, from abuse to liberation. Walker's use of Black Southern vernacular was revolutionary — Celie's voice grows in complexity as she ages.","Alice Walker","The Color Purple, first 40 letters",42,"Read the first 40 letters. Celie is 14 and pregnant by her father — she writes to God because she has no one else. The spelling is phonetic: 'I am fourteen years old. I have always been a good girl.' As Celie ages, her voice matures — the letters become longer, more analytical, more powerful. Notice the silence that surrounds female desire: Shug Avery teaches Celie that pleasure is possible. The novel earns its joy.",["American","Fiction","Epistolary","20th Century"],"the-color-purple"),

mk("BOOKS","Book","Sapiens (2014)","Yuval Noah Harari's nonfiction history of humankind — from the Cognitive Revolution (70,000 years ago) to the present. Originally published in Hebrew, it became an international bestseller with 23+ million copies sold. Harari argues that what made Homo sapiens dominant was our ability to believe in fictions: money, nations, laws, gods.","Yuval Noah Harari","Sapiens, Part One: The Cognitive Revolution",45,"Read Part One. Harari argues that 70,000 years ago, Sapiens developed language capable of describing things that don't exist — which let us cooperate in huge numbers. Notice his method: each chapter begins with a big claim, supports it with evidence, then undercuts it with a question. The book makes you feel both proud and horrified to be human — the Agricultural Revolution, Harari argues, was 'history's biggest fraud.'",["Israeli","Nonfiction","History","21st Century"],"sapiens"),

mk("BOOKS","Book","A Brief History of Time (1988)","Stephen Hawking's book about cosmology — from the Big Bang to black holes — written for general readers. It stayed on the Sunday Times bestseller list for 237 weeks. Hawking wrote it while almost completely paralyzed by ALS, dictating through a speech synthesizer. The book has sold over 25 million copies though many admit they never finished it.","Stephen Hawking","A Brief History of Time, chapters 1-3",40,"Read the first three chapters. Hawking starts with Aristotle and Ptolemy — our picture of the universe as a series of nested spheres. Then Galileo, Newton, Einstein, and the expanding universe. Notice how Hawking builds each concept on the last: you don't need math to follow the argument, just curiosity. The question at the center: why does the universe bother to exist?",["British","Nonfiction","Science","20th Century"],"a-brief-history-of-time"),

mk("BOOKS","Book","Demon Copperhead (2022)","Barbara Kingsolver's novel reimagining David Copperfield in modern Appalachia — a boy born to a teenage mother in a single-wide trailer in Lee County, Virginia. Won the Pulitzer and the Women's Prize. The novel is a direct response to the opioid crisis and the failure of institutions meant to protect children. Demon's voice is the novel's engine: wry, unbroken, irresistible.","Barbara Kingsolver","Demon Copperhead, first 10 chapters",50,"Read the first ten chapters. Demon is born in a trailer to a teenage mother who ODs early. He enters foster care — the system is the villain. Kingsolver follows Dickens's chapter structure exactly. Notice Demon's voice: he's telling his story as an adult looking back, with humor that never softens the horror. The foster homes, the child labor, the first pill — the novel is an indictment that reads like a page-turner.",["American","Fiction","Contemporary","21st Century"],"demon-copperhead"),

mk("BOOKS","Book","The Secret History (1992)","Donna Tartt's debut novel about a group of elite Classics students at a Vermont college who murder one of their own. The novel tells you who dies and who kills him on the first page — the suspense is why. Tartt wrote it over eight years at Bennington College. The novel launched the 'dark academia' aesthetic and has sold millions.","Donna Tartt","The Secret History, Book I",45,"Read Book I. Richard Papen arrives at Hampden College from a working-class California background and falls into a clique of beautiful, wealthy, morally untethered Classics students. Their professor Julian teaches them to live like the ancients. The first murder is presented as ritual, then necessity. Notice Tartt's atmosphere: the Vermont winter, the Greek declensions, the opium tea — beauty and decay are inseparable.",["American","Fiction","Mystery","20th Century"],"the-secret-history"),

mk("BOOKS","Book","Parable of the Sower (1993)","Octavia Butler's dystopian novel set in the 2020s — a world of climate collapse, corporate towns, and a populist president who promises to 'Make America Great Again.' The protagonist Lauren Olamina founds a religion called Earthseed whose first verse is 'God is Change.' Butler predicted our present with eerie accuracy from 1993. She died in 2006 at 58.","Octavia Butler","Parable of the Sower, first 5 chapters",35,"Read the first five chapters. Lauren is 15 when her walled community is destroyed. Her journal entries open each chapter with an Earthseed verse. She has 'hyperempathy' — she feels others' pain physically — which is a fatal weakness in a world of constant violence. The novel is a survival story, but the real engine is Lauren's idea: that change is the only constant, and the destination is the stars.",["American","Science Fiction","Dystopian","20th Century"],"parable-of-the-sower"),

mk("BOOKS","Book","The Sympathizer (2015)","Viet Thanh Nguyen's debut novel won the Pulitzer. It's a confession written by a half-French, half-Vietnamese communist spy who infiltrates the South Vietnamese army and flees to Los Angeles after the fall of Saigon. The novel is one long sentence of guilt, irony, and savage critique of both American intervention and Vietnamese communism.","Viet Thanh Nguyen","The Sympathizer, chapters 1-5",45,"Read the first five chapters. The narrator is a captain in the South Vietnamese army and a communist mole. He escapes Saigon on one of the last helicopters and lands in Los Angeles. Nguyen writes the entire novel in a confessional voice — the Captain is writing a forced confession in a reeducation camp. Notice the double vision: every event is seen from two ideological perspectives simultaneously. 'I am a spy, a sleeper, a spook, a man of two faces.'",["Vietnamese-American","Fiction","Historical","21st Century"],"the-sympathizer"),

mk("BOOKS","Book","Klara and the Sun (2021)","Kazuo Ishiguro's first novel after winning the Nobel Prize. It's narrated by Klara, an Artificial Friend — a solar-powered robot companion for children — who observes the world with luminous naivety. The novel is about love, sacrifice, and what happens when technology offers to replace what we've lost. Ishiguro said he wrote the book because he wanted to explore what it means to love without jealousy.","Kazuo Ishiguro","Klara and the Sun, Part One",38,"Read Part One. Klara stands in a store waiting to be chosen. She's solar-powered and worships the Sun as a god — she believes it gives her 'special nourishment.' Ishiguro writes from Klara's limited perspective: she processes the world in grids and boxes, and human emotions are puzzles she must solve. Notice how the prose never signals tragedy — like all Ishiguro narrators, Klara's innocence is the novel's devastating tool.",["British","Science Fiction","Literary","21st Century"],"klara-and-the-sun"),

mk("BOOKS","Book","Dune (1965)","Frank Herbert's science fiction novel set on the desert planet Arrakis — the only source of the spice melange, the most valuable substance in the universe. It was rejected by 20 publishers before being accepted by a publisher of car repair manuals. It's the best-selling science fiction novel of all time and inspired Star Wars, Game of Thrones, and ecological movements.","Frank Herbert","Dune, Book One: Dune",55,"Read Book One. Paul Atreides, ducal heir, arrives on Arrakis with his family — a trap set by their enemies. Herbert built a world as detailed as Tolkien's: the Fremen (desert dwellers), the sandworms, the stillsuit that recycles body moisture. Notice the ecological theme — every detail of Fremen culture is an adaptation to water scarcity. Paul's journey from boy to messiah is not heroic — it's a warning about charismatic leaders.",["American","Science Fiction","Epic","20th Century"],"dune"),

mk("BOOKS","Book","The Goldfinch (2013)","Donna Tartt's novel about a boy who survives a terrorist bombing at the Metropolitan Museum of Art and steals a 17th-century painting — Carel Fabritius's 'The Goldfinch.' The novel won the Pulitzer. It's 771 pages of grief, art theft, antique furniture restoration, and a friendship with a Ukrainian boy named Boris who may be the most alive character in contemporary fiction.","Donna Tartt","The Goldfinch, Part I",50,"Read Part I. Theo Decker, 13, loses his mother in a museum bombing. Dazed, he takes the painting — a small goldfinch chained to its perch. Tartt writes childhood trauma with Proustian density: every object in Theo's life becomes saturated with meaning. Boris, his school friend in Las Vegas, introduces Theo to vodka, drugs, and a philosophy of survival: 'We are two cockroaches, my friend.' The painting becomes Theo's religion.",["American","Fiction","Literary","21st Century"],"the-goldfinch"),

mk("BOOKS","Book","Slaughterhouse-Five (1969)","Kurt Vonnegut's anti-war novel based on his experience as a POW during the firebombing of Dresden — he was one of the few American soldiers to witness it, sheltered in an underground meat locker. The novel's structure — time-hopping, alien abduction — was Vonnegut's way of writing about trauma that couldn't be narrated linearly. He wrote it 23 years after the bombing.","Kurt Vonnegut","Slaughterhouse-Five, chapters 1-5",30,"Read the first five chapters. Billy Pilgrim has 'come unstuck in time.' The novel opens with Vonnegut as a character trying to write the book. Billy's time-traveling is not science fiction — it's PTSD. Each jump is triggered by something in the present: a barbershop quartet reminds him of the German soldiers grinning at the destruction of Dresden. 'So it goes' — the novel's refrain — appears 106 times. Every death is equal.",["American","Satire","Anti-War","20th Century"],"slaughterhouse-five"),

mk("BOOKS","Book","Americanah (2013)","Chimamanda Ngozi Adichie's novel about Ifemelu and Obinze, Nigerian teenagers in love who emigrate separately — she to America, he to London. Ifemelu starts a blog about race in America called 'Raceteenth.' The novel is about love, hair, race as a construct, and the decision to go home. Adichie said she wrote it because she was tired of reading American books where race was invisible.","Chimamanda Ngozi Adichie","Americanah, Part One",42,"Read Part One. Ifemelu, now a successful blogger in America, decides to return to Nigeria and braids her hair for the journey — the braiding salon chapters are a frame around the story. Adichie captures the shock of encountering American racial categories as an immigrant: 'I did not think of myself as black and I only became black when I came to America.' Notice the blog posts embedded in the novel — they're sharp, funny, and true.",["Nigerian","Fiction","Contemporary","21st Century"],"americanah"),

mk("BOOKS","Book","The Road (2006)","Cormac McCarthy's post-apocalyptic novel about a father and son walking through a dead America. The world has burned — nothing grows, no birds sing, and the only survivors are 'the good guys' and the cannibals. McCarthy wrote it for his own young son. Won the Pulitzer. The novel strips language to its bones: no chapter numbers, no quotation marks, barely any proper nouns.","Cormac McCarthy","The Road, the first half",35,"Read the first half. 'When he woke in the woods in the dark and the cold of the night he'd reach out to touch the child sleeping beside him.' The man and the boy push a shopping cart of scavenged goods. Their dialogue is minimalist, liturgical: 'We're carrying the fire.' Notice what McCarthy omits — character names, explanations of the catastrophe, interior monologue. The love is in what they do, not what they say.",["American","Fiction","Post-Apocalyptic","21st Century"],"the-road"),

mk("BOOKS","Book","The Underground Railroad (2016)","Colson Whitehead's novel that turns the metaphorical Underground Railroad into a literal train system running beneath the South — engineers, boxcars, tunnels. Won the Pulitzer and the National Book Award. Whitehead said the premise came from a childish misunderstanding: as a kid, he imagined the Railroad was real, and he wanted to honor that literal belief.","Colson Whitehead","The Underground Railroad, chapters 1-4",40,"Read the first four chapters. Cora, a slave on a Georgia cotton plantation, escapes on the Underground Railroad — an actual train beneath the soil. Each state she visits is a different iteration of American racism: South Carolina performs a genteel eugenics, North Carolina bans Black people entirely. Whitehead's prose is measured, terrifying, and unflinching. The railroad is a magnificent lie made real — and each stop is a new horror.",["American","Historical Fiction","Speculative","21st Century"],"the-underground-railroad"),

mk("BOOKS","Book","Erasure (2001)","Percival Everett's novel about a Black novelist who, enraged by the success of stereotypical 'ghetto fiction,' writes a parody of it under a pseudonym — which becomes a smash hit that the literary establishment takes seriously. The novel was adapted into the Oscar-winning film 'American Fiction' (2023).","Percival Everett","Erasure, first half",40,"Read the first half. Thelonious 'Monk' Ellison writes dense, literary novels that don't sell. Under the name Stagg R. Leigh, he writes 'My Pafology' (later retitled 'Fuck') — every stereotype in one book. The novel-within-a-novel is included in full — and it's hilarious and painful in equal measure. Notice how the publishing industry's embrace of the fake book implicates the reader too.",["American","Fiction","Satire","21st Century"],"erasure"),

mk("BOOKS","Book","Piranesi (2020)","Susanna Clarke's novel about a man living in an infinite House with marble halls, tides, and statues. He calls himself Piranesi, though that's not his name. He keeps meticulous journals and believes he's one of only two living people in the world. Clarke wrote it while housebound with chronic fatigue syndrome. It won the Women's Prize.","Susanna Clarke","Piranesi, Part One",30,"Read Part One. 'I am the Beloved Child of the House.' Piranesi explores the endless halls, catalogues the statues, fishes, and writes in his journals. His narration is gentle, precise, and happy — which is why the dawning horror is so effective. The House is both prison and paradise. Notice the capitalized nouns: the House, the Tides, the Other — Piranesi's worldview is a cosmology of one. The mystery of who he really is unfolds through journal entries.",["British","Fantasy","Literary","21st Century"],"piranesi"),

mk("BOOKS","Book","My Brilliant Friend (2011)","Elena Ferrante's first Neapolitan Novel — about Lila and Elena, two girls growing up in a poor Naples neighborhood in the 1950s. Lila is brilliant and dangerous; Elena is the diligent one who gets out. Their friendship is the central love story. The identity of the author — 'Elena Ferrante' is a pseudonym — remains unknown, though a journalist claimed to unmask her in 2016.","Elena Ferrante","My Brilliant Friend, Childhood + Adolescence",50,"Read the Childhood and Adolescence sections. Lila throws Elena's doll into a cellar. Elena does the same to Lila's. They descend into the darkness to retrieve them and Lila doesn't come back — the first of many disappearances. Ferrante writes girlhood as a war fought with grades, shoes, and the attention of boys. Notice the neighborhood (the rione) — it's a character, violent and intimate. Escape is possible, but the rione never lets you go.",["Italian","Fiction","Literary","21st Century"],"my-brilliant-friend"),

mk("BOOKS","Book","Station Eleven (2014)","Emily St. John Mandel's novel about a pandemic that collapses civilization — written years before COVID. A traveling Shakespeare troupe performs for survivor settlements 20 years after a Georgian flu killed 99% of humanity. The novel jumps between the pre-pandemic world and the post, connected by a graphic novel called 'Station Eleven' drawn by the actor Arthur Leander's first wife.","Emily St. John Mandel","Station Eleven, Parts 1-3",40,"Read Parts 1-3. Arthur Leander dies of a heart attack onstage during King Lear. That same night, the flu arrives. Twenty years later, Kirsten — a child actress who was on stage with Arthur that night — performs Shakespeare in the post-pandemic wilderness. Mandel makes the apocalypse beautiful: 'Survival is insufficient.' Notice the connections — every character is linked through Arthur, and survival depends on art.",["Canadian","Science Fiction","Literary","21st Century"],"station-eleven"),

mk("BOOKS","Book","The Odyssey (c. 8th century BCE)","The ancient Greek epic attributed to Homer — Odysseus's 10-year journey home from the Trojan War. Penelope fends off 108 suitors; Odysseus blinds the Cyclops, resists the Sirens, and descends into the underworld. Every road-trip story, every 'getting home' narrative, descends from this poem. It was composed to be sung, not read.","Homer","The Odyssey, Books 1-6",50,"Read Books 1-6. Odysseus is on Calypso's island, captive and weeping. Meanwhile in Ithaca, Penelope unweaves her father-in-law's shroud each night to delay choosing a new husband. Telemachus, the son who never knew his father, sets out to find news. Notice how Homer starts in the middle — the story is told through flashbacks and songs. The gods are childish, cruel, and hilarious. Athena's disguise as Mentor gave us the word.",["Greek","Epic Poetry","Classical","Ancient"],"the-odyssey"),

mk("BOOKS","Book","I Know Why the Caged Bird Sings (1969)","Maya Angelou's first memoir — covering her childhood from age 3 to 17 in Stamps, Arkansas. She was raped at 7 by her mother's boyfriend; after she testified and he was killed, she stopped speaking for five years, believing her voice had killed him. The memoir launched her career and was the first nonfiction bestseller by a Black woman.","Maya Angelou","I Know Why the Caged Bird Sings, chapters 1-15",45,"Read the first 15 chapters. Marguerite (later Maya) and her brother Bailey are sent alone on a train at ages 3 and 4 from California to Arkansas with tags pinned to their coats. Angelou's voice is the memoir's gift — she writes from childhood without simplifying childhood. The five years of silence after the assault: she read everything, memorized Shakespeare, and discovered that language could be a refuge. The caged bird sings not despite the cage but because of it.",["American","Memoir","Autobiography","20th Century"],"i-know-why-the-caged-bird-sings"),

mk("BOOKS","Book","The Hitchhiker's Guide to the Galaxy (1979)","Douglas Adams's comic science fiction novel that started as a BBC radio series. Arthur Dent is saved from Earth's destruction by his friend Ford Prefect — an alien researcher for the titular guidebook. The answer to life, the universe, and everything is 42. Adams wrote the first draft drunk in a field in Innsbruck. The novel has sold 14+ million copies.","Douglas Adams","The Hitchhiker's Guide to the Galaxy, chapters 1-10",30,"Read the first ten chapters. Arthur Dent's house is about to be demolished to make way for a bypass — the same morning the Earth is destroyed to make way for an interstellar bypass. Adams's humor is equal parts philosophy and absurdity. Notice the Guide entries — they're the funniest parts of the book, satirizing the tone of tourist guidebooks. The Vogon poetry scene is the worst torture in the galaxy. Don't panic.",["British","Science Fiction","Comedy","20th Century"],"the-hitchhikers-guide-to-the-galaxy"),

mk("BOOKS","Book","Half of a Yellow Sun (2006)","Chimamanda Ngozi Adichie's novel about the Biafran War (1967-70), told through three characters: Ugwu, a houseboy; Olanna, a wealthy woman; and Richard, a British writer. Adichie grew up in the house where the Biafran leader once lived; her grandfathers fought on opposite sides. The novel won the Women's Prize and was voted the best book to have won the award.","Chimamanda Ngozi Adichie","Half of a Yellow Sun, Part One: The Early Sixties",48,"Read Part One. The novel opens with Ugwu, a village boy, becoming a houseboy for Odenigbo, a radical professor. Olanna moves from Lagos to live with Odenigbo. The first half is domestic — dinner parties, love affairs, academic debates — and Adichie makes you love these characters before the war comes. Notice the shattering mid-novel reveal: the book has been withholding the worst thing that happens.",["Nigerian","Historical Fiction","Literary","21st Century"],"half-of-a-yellow-sun"),

mk("BOOKS","Book","The Virgin Suicides (1993)","Jeffrey Eugenides's debut novel about the five Lisbon sisters who kill themselves over the course of a year in 1970s suburban Michigan. The novel is narrated by the neighborhood boys, now middle-aged, still obsessed and clueless. Eugenides wrote it in a single summer while working as a secretary.","Jeffrey Eugenides","The Virgin Suicides, the whole novel",35,"Read the whole novel — it's short, under 250 pages. The boys narrate as a collective 'we' — they never become individuals. They watch the Lisbon girls from across the street, collect their belongings, and 20 years later still can't understand. Notice the epistolary elements: doctor's reports, diary entries, photographs. The girls remain opaque — the novel is about the failure to understand, and the beauty in that failure. 'They made us participate in their own madness.'",["American","Fiction","Literary","20th Century"],"the-virgin-suicides"),

mk("BOOKS","Book","Crying in H Mart (2021)","Michelle Zauner's memoir about losing her Korean mother to cancer and finding her identity in Korean food. Zauner is better known as the musician Japanese Breakfast. The book became a #1 New York Times bestseller. H Mart is an Asian supermarket chain — the title comes from the experience of crying in the food court because every item reminds you of your dead mother.","Michelle Zauner","Crying in H Mart, the whole memoir",45,"Read the whole memoir. Zauner's mother is diagnosed with cancer when Michelle is 25. The memoir moves between the illness, Zauner's childhood in Eugene, Oregon, her rebellious teenage years, and the ritual of cooking Korean food to keep her mother present. Notice the food descriptions — they're precise, physical, and spiritual. Making kimchi becomes a form of grief. The book is a reminder that love lives in the body and the kitchen.",["Korean-American","Memoir","Nonfiction","21st Century"],"crying-in-h-mart"),

mk("BOOKS","Book","The Power (2016)","Nina Alderman's novel about a world where women suddenly develop the ability to emit electric shocks from their hands — upending every power structure. The novel is framed as a manuscript written 5,000 years in the future by a male historian in a matriarchal world. Won the Women's Prize. It reads like a thriller and thinks like a philosophical treatise.","Naomi Alderman","The Power, Book One",38,"Read Book One. Teenage girls around the world discover the power — a skein of electricity they can discharge at will. The novel follows four characters: a British foster kid, an American politician's daughter, a Nigerian journalist, and a Moldovan trafficker's son. Alderman makes the premise chillingly plausible — within weeks, the world reorganizes. Notice the frame: letters between 'Neil' and 'Naomi' in a future where men are the weaker sex, and their historical revisionism is the mirror of ours.",["British","Science Fiction","Feminist","21st Century"],"the-power"),

mk("BOOKS","Book","Homegoing (2016)","Yaa Gyasi's debut novel spanning 300 years — from the Gold Coast (Ghana) to modern America. Each chapter is a new generation descended from two half-sisters: one married to a British slave trader, one sold into slavery. Gyasi wrote it at 25 after a research trip to Ghana. The novel does in 300 pages what most family sagas do in 800.","Yaa Gyasi","Homegoing, the whole novel",50,"Read the whole novel — each chapter is a generation. Effia marries a British governor of Cape Coast Castle; her half-sister Esi is held in the dungeon below the same castle, then shipped to America. Each chapter is a complete short story about one descendant. The structure is a chain: you lose each character after one chapter, but their children carry the inheritance. Notice the recurring fire and water imagery — it runs through the bloodline like a scar.",["Ghanaian-American","Historical Fiction","Literary","21st Century"],"homegoing"),

mk("BOOKS","Book","The Vanishing Half (2020)","Brit Bennett's novel about identical twin sisters from a small Black town in Louisiana — one lives as a Black woman, the other passes for white. Their daughters' lives intersect years later. The novel explores race as performance, identity as choice, and what we owe to where we came from. It was an instant #1 bestseller and HBO adapted it.","Brit Bennett","The Vanishing Half, Parts I-II",40,"Read Parts I and II. The Vignes twins run away from Mallard, Louisiana — a town so light-skinned it was founded on colorism. Desiree returns years later with a 'blue-black' daughter. Stella has disappeared into whiteness — her new life in Brentwood, California is built on a lie she can never confess. Bennett writes passing not as deception but as grief: Stella loses her twin, her mother, her town, and eventually herself.",["American","Fiction","Literary","21st Century"],"the-vanishing-half"),

mk("BOOKS","Book","White Teeth (2000)","Zadie Smith's debut novel written during her final year at Cambridge. It follows two wartime friends — Archie Jones (English) and Samad Iqbal (Bangladeshi) — and their families in multicultural London from 1975 to 2000. The novel was auctioned for a six-figure advance based on 80 pages. Critics called it a masterpiece; Smith later called its ending 'literary suicide.'","Zadie Smith","White Teeth, Part One: Archie 1974, 1945",38,"Read Part One. Archie tries to gas himself in his car but is saved by a halal butcher. He marries Clara, a Jamaican Jehovah's Witness half his age. Smith writes London's diversity as chaotic joy — her prose is elastic, moving from street slang to Latinate sentences in the same paragraph. Notice the obsession with roots, teeth, and inheritance — can you escape history or are you doomed to repeat it? The novel answers 'both.'",["British","Fiction","Contemporary","21st Century"],"white-teeth"),
]
added += append_batch("books.json", b3, "BOOKS")
print(f"Cumulative added: {added} | Authors: {count('authors.json')} | Books: {count('books.json')}")
