#!/usr/bin/env python3
"""Generate remaining authors (224) and books (208) to each reach 400+."""
import json
from pathlib import Path

TOPICS_DIR = Path("app/src/main/assets/topics")

def mk(cat, subtype, name, teaser, byline, target, mins, instr, tags, slug, tier=2):
    e = {"id":f"{'author' if cat=='AUTHORS' else 'book'}-{slug}","categoryId":cat,
         "subtype":subtype,"name":name,"teaser":teaser,"imageUrl":""}
    if byline: e["byline"] = byline
    e["exploreAction"] = {"verb":"Read","targetName":target,"durationMinutes":mins,"instruction":instr}
    e["tags"] = tags; e["tier"] = tier; return e

def append_batch(fname, batch, cat):
    path = TOPICS_DIR / fname
    existing = json.loads(path.read_text())
    ids = {e["id"] for e in existing}
    new = [e for e in batch if e["id"] not in ids]
    if not new: print(f"  {fname}: skipped {len(batch)}"); return 0, []
    existing.extend(new)
    path.write_text(json.dumps(existing, indent=2, ensure_ascii=False) + "\n")
    print(f"  {fname}: +{len(new)} => {len(existing)}")
    return len(new), [e["id"] for e in new]

print("=== Starting bulk generation ===")
a_count = len(json.loads((TOPICS_DIR / "authors.json").read_text()))
b_count = len(json.loads((TOPICS_DIR / "books.json").read_text()))
print(f"Authors before: {a_count} | Books before: {b_count}")
total = 0


# ===== AUTHORS BATCH 4 (40) =====
print("\n--- Authors Batch 4 ---")
a4 = [
mk("AUTHORS","Author","Oscar Wilde","Irish playwright and wit whose only novel 'The Picture of Dorian Gray' (1890) was used as evidence against him at his trial for 'gross indecency.' He was sentenced to two years of hard labor. His prison letter 'De Profundis' is one of the most devastating documents of the 19th century. He died penniless in Paris at 46.","","The Importance of Being Earnest, the whole play",35,"Read the whole play. Two men pretend to be named Ernest to woo two women who will only marry an Ernest. Wilde's dialogue is champagne — every line is a quotable paradox. 'The truth is rarely pure and never simple.' Notice that beneath the comedy, Wilde is attacking Victorian marriage, class, and morality. The play's subtitle is 'A Trivial Comedy for Serious People.'",["Irish","Drama","Comedy","19th Century"],"oscar-wilde"),

mk("AUTHORS","Author","Marcel Proust","French novelist who wrote 'In Search of Lost Time' — seven volumes, 1.2 million words — while bedridden in a cork-lined room, dying of asthma. A madeleine dipped in tea triggers the entire novel. He spent the last three years of his life rewriting the ending. The novel was rejected by multiple publishers; he published the first volume at his own expense.","","Swann's Way, the first section: Combray",40,"Read the Combray section. The narrator bites into a madeleine dipped in tea and his entire childhood in the village of Combray floods back. Proust's sentences are famously long — they spiral, subordinate, return — but they're built to reproduce the texture of consciousness. The Overture (first 50 pages) is about a man who can't fall asleep. Everything follows from that insomnia.",["French","Fiction","Modernist","20th Century"],"marcel-proust"),

mk("AUTHORS","Author","Sylvia Plath","American poet and novelist whose only novel 'The Bell Jar' (1963) was published under a pseudonym one month before her suicide at 30. She wrote it in the early mornings before her children woke, in a fury. Her posthumous poetry collection 'Ariel' (1965) made her one of the most influential poets since WWII. Her husband Ted Hughes became Poet Laureate and controlled her estate for decades.","","The Bell Jar, chapters 1-7",30,"Read the first seven chapters. Esther Greenwood is in New York on a magazine internship, and she should be having the time of her life. She isn't. Plath's prose is glittering and clinical — depression is described from the inside with eerie lucidity. 'I felt very still and very empty, the way the eye of a tornado must feel.' The bell jar descends without Esther noticing.",["American","Poetry","Fiction","20th Century"],"sylvia-plath"),

mk("AUTHORS","Author","Kazuo Ishiguro","British novelist born in Nagasaki who won the Nobel Prize in 2017. His narrators are famously unreliable not because they lie but because they're lying to themselves. 'The Remains of the Day' (1989) was written in a four-week 'crash' — he locked himself away and wrote all day, every day, to keep the butler's voice consistent.","","Never Let Me Go, the whole novel",50,"Read the whole novel. Kathy H. narrates her life at Hailsham, an idyllic boarding school with a dark purpose. Ishiguro wrote it as a metaphor for mortality — the students are clones raised for organ donation, but the novel never uses that word. Notice the flatness of Kathy's narration: the horror is never named because Kathy was raised to accept it. The tragedy is that she never questions her purpose.",["British","Fiction","Literary","21st Century"],"kazuo-ishiguro"),

mk("AUTHORS","Author","Edwidge Danticat","Haitian-American novelist who published her first novel 'Breath, Eyes, Memory' (1994) at 25 — Oprah picked it for her book club, catapulting Danticat to fame. She was born in Haiti and sent to Brooklyn at 12 to join parents she barely remembered. Her fiction excavates the Haitian diaspora, political violence, and the complicated love between mothers and daughters.","","Krik? Krak!, the first 5 stories",38,"Read the first five stories. Each story is connected — characters from one reappear in another. 'Children of the Sea' is a series of letters between lovers on a sinking boat and in a Port-au-Prince under siege. Danticat writes Haiti not as victim but as resilience: the storytelling tradition (krik? krak!) is the survival. The epilogue 'Women Like Us' is a manifesto for why Haitian women write.",["Haitian-American","Fiction","Short Stories","20th Century"],"edwidge-danticat"),

mk("AUTHORS","Author","Vladimir Nabokov","Russian-American novelist, lepidopterist, and synesthete. He wrote 'Lolita' (1955) while on butterfly-collecting trips across America, composing on index cards in motel rooms. Every American publisher rejected it; it was first published by a Parisian press specializing in erotica. Nabokov insisted Lolita was not about sex but about the abuse of language — Humbert's beautiful prose seduces the reader as he seduces Dolores.","","Lolita, Part One",40,"Read Part One. Humbert Humbert narrates in French-inflected English so beautiful it's dangerous: 'Lolita, light of my life, fire of my loins.' Nabokov is making you complicit — Humbert's charm is the novel's trap. Notice how Humbert never describes what Lolita is feeling. The novel isn't a love story; it's a confession dressed as one. Nabokov plants clues of Humbert's monstrosity from page one.",["Russian-American","Fiction","Literary","20th Century"],"vladimir-nabokov"),

mk("AUTHORS","Author","Sally Rooney","Irish novelist who published her debut 'Conversations with Friends' (2017) at 26 and was called 'the first great millennial novelist.' Her novels are about sex, class, and political conviction among young Irish people. Her third novel 'Beautiful World, Where Are You' (2021) incorporates emails debating Marxism and the purpose of art between the sex scenes.","","Normal People, the whole novel",45,"Read the whole novel. Connell and Marianne — he's popular, she's weird — pretend not to know each other at school, then meet again at Trinity College where their roles reverse. Rooney writes without quotation marks and with surgical precision about class and desire. Notice the silences: Connell can't say what he feels, and the novel orbits around those unsaid sentences like a planet around a black hole.",["Irish","Fiction","Contemporary","21st Century"],"sally-rooney"),

mk("AUTHORS","Author","Samuel Beckett","Irish playwright and novelist who wrote 'Waiting for Godot' (1953) — a play where nothing happens, twice — and changed theater forever. He fought in the French Resistance during WWII and was awarded the Croix de Guerre. He won the Nobel Prize in 1969, but his wife called it a 'catastrophe' because he hated attention. He started writing in French because he wanted to write 'without style.'","","Waiting for Godot, Act I",35,"Read Act I. Two men, Vladimir and Estragon, wait by a bare tree for someone named Godot who never comes. Beckett's stage directions are as poetic as the dialogue. The play is a comedy about despair: they consider hanging themselves but can't find the rope. 'Let's go.' 'We can't.' 'Why not?' 'We're waiting for Godot.' Notice the repetitions — the structure is musical, not narrative.",["Irish","Drama","Absurdist","20th Century"],"samuel-beckett"),

mk("AUTHORS","Author","Annie Ernaux","French writer who won the Nobel Prize in 2022. She invented a genre she calls 'autosociobiography' — writing her own life as a document of class, gender, and time. Her novel 'The Years' (2008) is written without the pronoun 'I' — it's a collective autobiography of postwar France told through objects, songs, and meals.","","The Years, first half",42,"Read the first half. There is no 'I' — the narrator is 'we' and 'she,' describing a generation through photographs, advertisements, political slogans. Ernaux's prose is flat and forensic; she describes a family dinner with the same clinical precision as a political protest. Notice how public events (Algerian War, May '68, Mitterrand's election) intrude on private life like weather.",["French","Memoir","Literary","21st Century"],"annie-ernaux"),

mk("AUTHORS","Author","James Joyce","Irish novelist who wrote 'Ulysses' (1922) — set on a single day (June 16, 1904) in Dublin, following Leopold Bloom. The novel was banned in the US and UK for obscenity; the first edition was smuggled into America in copies of a magazine. Joyce had terrible eyesight and wrote on large sheets of paper with colored crayons. His last words were reportedly 'Does nobody understand?'","","Dubliners, the story 'The Dead'",30,"Read 'The Dead' — the final story in Dubliners, widely considered the greatest short story in English. Gabriel Conroy attends his aunts' annual Christmas party and learns his wife Gretta still mourns a boy who died for her love years ago. The final paragraph — snow falling 'upon all the living and the dead' — is one of the most beautiful passages in literature. Notice the shift: Gabriel starts the story feeling superior and ends it feeling nothing.",["Irish","Fiction","Modernist","20th Century"],"james-joyce"),

mk("AUTHORS","Author","Svetlana Alexievich","Belarusian journalist who won the Nobel Prize in Literature (2015) for her polyphonic oral histories — books composed entirely of interviews, edited into choruses. 'Voices from Chernobyl' (1997) is a collage of testimonies from the nuclear disaster: firefighters, widows, children, liquidators. She was persecuted by the Lukashenko regime and now lives in exile.","","Voices from Chernobyl, the first section",40,"Read the first section. Firefighters' wives describe watching their husbands die of radiation poisoning — the skin sloughing off, the internal organs turning to liquid. Alexievich edits the interviews into monologues that read like poetry. There is no narrator; the survivors speak directly. Notice how the form itself is the argument: only a chorus can hold a catastrophe this large.",["Belarusian","Nonfiction","Oral History","21st Century"],"svetlana-alexievich"),

mk("AUTHORS","Author","Mark Twain","American novelist and humorist born Samuel Clemens — his pen name 'Mark Twain' is riverboat slang for 'two fathoms deep' (safe water). His novel 'Adventures of Huckleberry Finn' (1884) was banned from the Concord Public Library the month it was published. Hemingway said all American literature comes from one book: Huckleberry Finn.","","Adventures of Huckleberry Finn, chapters 1-11",40,"Read the first eleven chapters. Huck narrates in his own dialect — Twain pioneered American vernacular in literature. Huck fakes his own murder and escapes on the Mississippi with Jim, a slave running toward freedom. Notice Huck's moral crisis: society has taught him that helping Jim is a sin, but his heart says otherwise. The river is freedom; the shore is hypocrisy.",["American","Fiction","Satire","19th Century"],"mark-twain"),

mk("AUTHORS","Author","Kobo Abe","Japanese novelist who wrote 'The Woman in the Dunes' (1962) — about a man trapped in a sand pit with a woman who has accepted her captivity. The novel is part Kafka, part existential horror, and completely its own thing. Abe was also a playwright and photographer. He was a member of the Japanese Communist Party until he was expelled for criticizing the Soviet Union.","","The Woman in the Dunes, the whole novel",42,"Read the whole novel. An entomologist is tricked into descending a rope ladder into a sand pit — the ladder is removed, and he's trapped with a woman whose job is to shovel sand every night. The sand is the novel's real protagonist: it seeps into everything, rots wood, rubs skin raw. Notice how Abe writes captivity as a kind of strange freedom — the man eventually stops trying to escape.",["Japanese","Fiction","Existential","20th Century"],"kobo-abe"),

mk("AUTHORS","Author","Per Petterson","Norwegian novelist whose 'Out Stealing Horses' (2003) won the IMPAC Dublin Award and was named one of the 10 best books of the year by the New York Times. The novel is about a 67-year-old man who moves to a remote cabin after his wife's death and remembers a summer in 1948 that changed everything. Petterson's family died in the Scandinavian Star ferry disaster (1990); the novel is shadowed by loss.","","Out Stealing Horses, the whole novel",45,"Read the whole novel — it's short and devastating. Trond, 67, has retreated to a cabin in the Norwegian woods. A neighbor's voice triggers a memory of the summer he was 15, when he and his friend Jon went 'out stealing horses' — which really meant joyriding on other people's animals. The novel moves between 1999 and 1948 without signaling the shifts. Petterson writes about fathers and sons with Hemingway's restraint and Chekhov's tenderness.",["Norwegian","Fiction","Literary","21st Century"],"per-petterson"),

mk("AUTHORS","Author","Audre Lorde","American poet, essayist, and activist who described herself as 'Black, lesbian, mother, warrior, poet.' Her essay collection 'Sister Outsider' (1984) includes 'The Master's Tools Will Never Dismantle the Master's House' and 'Poetry Is Not a Luxury.' She died of breast cancer at 58. Her work theorized difference — race, gender, sexuality, class — as a source of power, not division.","","Sister Outsider, essays 1-5",38,"Read the first five essays. 'Poetry Is Not a Luxury' argues that poetry is not decoration but survival — it names the unnamed so we can act on it. Lorde writes theory as testimony: every abstraction is grounded in lived experience. Notice her prose rhythm — it builds like a sermon but argues like a lawyer. The anger is precise, never performative.",["American","Poetry","Essays","20th Century"],"audre-lorde"),

mk("AUTHORS","Author","Mohsin Hamid","Pakistani-British novelist whose 'Exit West' (2017) tells a love story amid a refugee crisis — but the doors between countries are magical portals. The novel was shortlisted for the Booker. Hamid also wrote 'The Reluctant Fundamentalist' (2007), a monologue addressed by a Pakistani man to an American stranger in a Lahore cafe that builds into a thriller.","","Exit West, the whole novel",35,"Read the whole novel — it's under 250 pages. Nadia and Saeed fall in love as their unnamed city collapses into civil war. They escape through magical doors that open to Mykonos, then London, then Marin County. Hamid writes the doors matter-of-factly — the magic is not explained, just accepted. Notice the narrative voice: omniscient and philosophical, describing entire lives in a single paragraph, then zooming in on a kiss.",["Pakistani-British","Fiction","Speculative","21st Century"],"mohsin-hamid"),

mk("AUTHORS","Author","Ray Bradbury","American science fiction writer who wrote 'Fahrenheit 451' (1953) on a rented typewriter in the basement of the UCLA library — it cost 10 cents per half hour, and the total cost to write the novel was $9.80. The novel is about a future where books are burned, and it began as a short story called 'The Fireman' in Galaxy Science Fiction.","","Fahrenheit 451, Part One",28,"Read Part One: 'The Hearth and the Salamander.' Guy Montag is a fireman whose job is to burn books. He meets Clarisse, a 17-year-old who asks 'Are you happy?' — and the question unmoors him. Bradbury wrote the novel in nine days. Notice the sensory overload: walls that are giant television screens, seashell radios in ears, and the scent of kerosene. The novel is a love letter to books disguised as a warning about them.",["American","Science Fiction","Dystopian","20th Century"],"ray-bradbury"),

mk("AUTHORS","Author","Mikhail Bulgakov","Russian novelist and playwright whose masterpiece 'The Master and Margarita' was written during Stalin's Great Terror, hidden in a drawer, and published 26 years after his death. Stalin personally liked one of Bulgakov's early plays — which probably saved his life, though it didn't save his career. He called Stalin, then dictated a plea to be allowed to emigrate. Stalin called back and got him a job.","","Heart of a Dog, the whole novella",25,"Read Heart of a Dog — it's short. A Moscow professor implants human testicles into a stray dog, who slowly becomes a crude Soviet bureaucrat named Sharikov. The novella is a savage satire of the Soviet project to create a 'New Soviet Man.' Bulgakov wrote it in 1925; it was immediately banned and not published in the USSR until 1987. The dog's narration is the funniest writing Bulgakov ever did.",["Russian","Fiction","Satire","20th Century"],"mikhail-bulgakov"),

mk("AUTHORS","Author","Colm Toibin","Irish novelist whose 'Brooklyn' (2009) follows Eilis Lacey, a young Irish woman who emigrates to 1950s Brooklyn — and must choose between two lives, two countries, two loves. The novel is a miracle of restraint: Toibin never tells you what Eilis is feeling; he shows you what she does. It was adapted into an Oscar-nominated film in 2015.","","Brooklyn, Part One",35,"Read Part One. Eilis leaves Enniscorthy for Brooklyn, traveling steerage, sharing a bathroom with strangers. Toibin's prose is so restrained it's almost invisible — you learn Eilis's inner life through what she eats, what she wears, how long she hesitates before opening a letter. The novel captures emigration as a series of small griefs: the taste of food, the sound of your own accent fading.",["Irish","Fiction","Historical","21st Century"],"colm-toibin"),

mk("AUTHORS","Author","Ken Liu","Chinese-American science fiction writer and translator who brought Liu Cixin's 'The Three-Body Problem' into English — the translation won the Hugo Award. His short story collection 'The Paper Menagerie' (2016) won multiple awards and is the only work of fiction to win the Hugo, Nebula, and World Fantasy Award for the same story.","","The Paper Menagerie, the title story",20,"Read 'The Paper Menagerie.' A Chinese-American boy's mother folds origami animals that come to life. As he grows older, he rejects her and her 'weird' culture. When she dies, he discovers a letter she wrote in Chinese he can no longer read. Liu uses fantasy to explore the tragedy of assimilation: the paper menagerie is a magic that costs the mother her life. The ending will break you.",["Chinese-American","Science Fiction","Fantasy","21st Century"],"ken-liu"),

mk("AUTHORS","Author","Nawal El Saadawi","Egyptian feminist writer and psychiatrist who was imprisoned in 1981 for 'crimes against the state' — her crime was writing about female genital mutilation, which she experienced at age 6. She wrote 'Memoirs from the Women's Prison' on toilet paper with an eyebrow pencil. Her novel 'Woman at Point Zero' (1975) is based on a real woman she met in prison who was executed for killing her pimp.","","Woman at Point Zero, the whole novel",30,"Read the whole novel — it's short and devastating. A psychiatrist (El Saadawi herself) interviews Firdaus, a woman on death row who refuses to appeal her sentence. Firdaus's life is a catalogue of male violence — uncle, husband, pimp — until she becomes a prostitute and discovers the only power women have: men will pay for her body. El Saadawi writes Firdaus's rage as clarity, not madness. Her final refusal is a kind of freedom.",["Egyptian","Fiction","Feminist","20th Century"],"nawal-el-saadawi"),

mk("AUTHORS","Author","Terry Pratchett","British fantasy author who wrote the 41-novel Discworld series — a flat world balanced on four elephants standing on a giant turtle. His books are comedy that becomes philosophy if you're not careful. He sold over 85 million copies worldwide and was knighted in 2009. After being diagnosed with early-onset Alzheimer's, he campaigned for assisted dying and made a documentary about it.","","Guards! Guards!, the whole novel",42,"Read Guards! Guards! Vimes, captain of the Night Watch — a cynical drunk in a city that doesn't want police — must stop a 60-foot dragon summoned by a secret society. Pratchett's worldbuilding is a joke-delivery system for ideas about power, justice, and why people obey bad laws. Vimes's 'Boots Theory of Socioeconomic Unfairness' is a better economics lesson than most textbooks. The humor is never cruel.",["British","Fantasy","Satire","20th Century"],"terry-pratchett"),

mk("AUTHORS","Author","Eudora Welty","American short story writer and novelist from Mississippi who won the Pulitzer in 1973. She worked as a photographer for the WPA during the Depression, documenting rural Mississippi. Her story 'Why I Live at the P.O.' is the funniest monologue in American literature — narrated by a woman so aggrieved by her family that she moves into the post office where she works.","","The Collected Stories, first 5 stories",38,"Read the first five stories. 'Why I Live at the P.O.' — Sister narrates how her sister Stella-Rondo came home with an adopted child and turned the whole family against her. Welty's ear for Southern speech is perfect: the exaggerations, the self-pity, the dramatic exits. Her characters talk themselves into and out of revelation. Notice the humor never undercuts the loneliness — the post office is a fortress of grievance.",["American","Fiction","Short Stories","20th Century"],"eudora-welty"),

mk("AUTHORS","Author","Graham Greene","British novelist and Catholic convert who divided his books into 'novels' and 'entertainments' — though the line was always blurry. He was a spy for MI6 during WWII, stationed in Sierra Leone and Portugal. His novel 'The Quiet American' (1955) predicted American failure in Vietnam years before the war escalated. He was shortlisted for the Nobel Prize multiple times but never won.","","The Power and the Glory, Part One",35,"Read Part One. A nameless 'whisky priest' — the last priest in a Mexican state that has outlawed religion — flees across the countryside, pursued by a police lieutenant. Greene's Catholicism is the novel's engine: the priest is a sinner (drunk, father of a child) but also a priest. His martyrdom is accidental and reluctant. Notice the scorching heat — Greene makes Mexico feel like hell with beautiful beaches.",["British","Fiction","Literary","20th Century"],"graham-greene"),

mk("AUTHORS","Author","N.K. Jemisin","American science fiction and fantasy writer who won the Hugo Award for Best Novel three years in a row (2016-2018) — the first author, male or female, to do so. Her Broken Earth trilogy opens with 'The Fifth Season' (2015), set on a planet wracked by apocalyptic seismic events, and written partly in second person. Jemisin is also a counseling psychologist.","","The Fifth Season, chapters 1-5",40,"Read the first five chapters. The novel opens: 'This is the way the world ends. Again.' Essun discovers her son murdered by his own father and sets out for revenge across a continent fracturing into apocalypse. Jemisin uses three narrative strands — one in second person — that the reader slowly realizes are connected in an impossible way. The geology is rigorous, the oppression systemic, and the voice is searing.",["American","Fantasy","Science Fiction","21st Century"],"nk-jemisin"),

mk("AUTHORS","Author","John Cheever","American short story writer called 'the Chekhov of the suburbs.' His stories chronicle mid-century American life — Westchester commuters, summer cocktail parties, the quiet desperation behind manicured lawns. He was an alcoholic and bisexual, facts he hid from most people. His journals, published posthumously, revealed the anguish behind the polished fiction.","","The Swimmer, plus 3 other stories",30,"Read 'The Swimmer' and three other stories. Neddy Merrill decides to swim home across the county by going pool to pool. As he progresses, the season changes — it's summer at the first pool, autumn at the last. Cheever makes the surreal plausible: the story is about a man swimming through his own life, and each pool is a memory. The ending is a door that won't open.",["American","Fiction","Short Stories","20th Century"],"john-cheever"),

mk("AUTHORS","Author","Natalia Ginzburg","Italian novelist and essayist who grew up in an antifascist household in Turin — her father was a famous biologist, her brothers were arrested for anti-Mussolini activities. Her first husband was tortured to death by the Nazis in 1944. Her essays ('The Little Virtues,' 1962) write about marriage, children, and writing with brutal clarity. Her prose sounds translated from a language where euphemism doesn't exist.","","The Little Virtues, the first 3 essays",25,"Read the first three essays. 'Winter in the Abruzzi' is about the wartime exile of her family in a mountain village — a time of poverty and fear that she remembers as paradise. Ginzburg writes about her children with no sentimentality: 'They are small despots.' Notice the economy: her essays are short because she has removed everything decorative. What remains is truth, plain and almost unbearable.",["Italian","Fiction","Essays","20th Century"],"natalia-ginzburg"),

mk("AUTHORS","Author","Sherman Alexie","Native American (Spokane-Coeur d'Alene) novelist, poet, and filmmaker. His YA novel 'The Absolutely True Diary of a Part-Time Indian' (2007) is semi-autobiographical — about a boy who leaves his reservation school for a white town 22 miles away. The novel was one of the most banned books in American schools. Alexie was born hydrocephalic and survived surgery at 6 months.","","The Absolutely True Diary of a Part-Time Indian, the whole book",35,"Read the whole book — it's a fast read with cartoons by Ellen Forney. Junior, 14, throws a textbook at his teacher and is told to leave the rez if he wants to survive. He transfers to Reardan High, where he's the only Indian except the school mascot. Alexie writes about poverty, basketball, death, and hope with absolute honesty. The cartoons make the sadness bearable. The rez and Reardan are different planets orbiting the same tragedy.",["Native American","Fiction","Young Adult","21st Century"],"sherman-alexie"),

mk("AUTHORS","Author","Anne Carson","Canadian poet, classicist, and essayist whose 'Autobiography of Red' (1998) retells the Greek myth of Geryon — a red-winged monster killed by Herakles — as a queer coming-of-age novel in verse. Carson is a professor of ancient Greek and translates her own work. Her essays blend classical scholarship, philosophy, and memoir until the genres dissolve. She won the Princess of Asturias Award in 2020.","","Autobiography of Red, the whole novel",40,"Read Autobiography of Red — it's a novel in verse. Geryon is a boy with red wings who keeps a photographic autobiography. Herakles arrives and breaks his heart. Carson's lines are gem-hard: 'He came after Homer and before Gertrude Stein.' The novel is about the violence of love and the persistence of monsters. Notice the interview with Stesichorus — the ancient poet who first wrote about Geryon — woven into the text like a scar.",["Canadian","Poetry","Fiction","21st Century"],"anne-carson"),

mk("AUTHORS","Author","Mario Vargas Llosa","Peruvian novelist who won the Nobel Prize in 2010. He ran for president of Peru in 1990 and lost to Alberto Fujimori. His novel 'The Feast of the Goat' (2000) is about the assassination of Dominican dictator Rafael Trujillo and the 30-year trauma that followed. Vargas Llosa writes fiction, journalism, and criticism with equal intensity — he once punched Gabriel Garcia Marquez in the face at a movie premiere.","","The Feast of the Goat, Part One",45,"Read Part One. Urania Cabral, now a successful lawyer in New York, returns to the Dominican Republic after 35 years to confront her father. The novel cuts between Urania's memories, the assassins plotting Trujillo's murder, and Trujillo himself. Vargas Llosa makes the dictator terrifyingly human — vain, aging, incontinent. Urania has a secret that explains why she fled and never returned. The novel builds toward it like a thunderstorm.",["Peruvian","Fiction","Historical","21st Century"],"mario-vargas-llosa"),

mk("AUTHORS","Author","Claire Keegan","Irish short story writer whose novellas are so perfectly compressed they feel carved. 'Foster' (2010) is about a girl sent to live with foster parents on a farm in rural Ireland one summer — nothing much happens and everything changes. The novella was published as a New Yorker story, then expanded. Keegan's sentences are so clean you don't notice them working.","","Foster, the whole novella",30,"Read Foster — it's about 90 pages. A girl is dropped off at a farm in Wexford while her mother gives birth. The Kinsellas treat her with a tenderness she's never known. Keegan tells the story entirely through the girl's perception — she doesn't understand what she's seeing, but the reader does. Notice what's withheld: a dead child, a secret grief, and the final sentence that redefines everything before it.",["Irish","Fiction","Literary","21st Century"],"claire-keegan"),

mk("AUTHORS","Author","Rainer Maria Rilke","Bohemian-Austrian poet who wrote 'Letters to a Young Poet' (1929) — 10 letters to a teenage military cadet asking for writing advice. Rilke's response: don't ask if your poems are good; ask 'Must I write?' He lived in a castle in Duino (where he heard the first line of the Duino Elegies in a storm) and died of leukemia at 51. His epitaph: 'Rose, oh pure contradiction.'","","Letters to a Young Poet, all 10 letters",35,"Read all 10 letters. Rilke tells the young poet to go into himself, to love the questions, to be patient with what is unresolved. His advice is for anyone making anything. 'Perhaps all the dragons in our lives are princesses who are only waiting to see us act, just once, with beauty and courage.' Notice the intimacy — Rilke writes to a stranger as if they are the only reader who matters.",["Austrian","Poetry","Letters","20th Century"],"rainer-maria-rilke"),

mk("AUTHORS","Author","Edgar Allan Poe","American writer who invented the detective story ('The Murders in the Rue Morgue,' 1841) and perfected the Gothic tale. He married his 13-year-old cousin Virginia; she died of tuberculosis at 24, and his writing never recovered. He was found delirious on a Baltimore street in someone else's clothes and died days later at 40. His cause of death remains unknown.","","The Fall of the House of Usher, plus 3 other stories",30,"Read 'The Fall of the House of Usher' and 3 other stories. The narrator visits Roderick Usher, a childhood friend succumbing to a mysterious illness in a decaying mansion. The house itself is sentient — its crack is a character. Poe's prose is Gothic in the architectural sense: every sentence builds toward dread. 'The Tell-Tale Heart' and 'The Cask of Amontillado' are master classes in unreliable narration.",["American","Fiction","Gothic","19th Century"],"edgar-allan-poe"),

mk("AUTHORS","Author","Bernardine Evaristo","British novelist who won the Booker Prize in 2019 for 'Girl, Woman, Other' — a polyphonic novel following 12 characters, mostly Black British women. Evaristo was the first Black woman to win the Booker. The novel is written in a form she calls 'fusion fiction' — somewhere between prose and poetry, with no periods, letting the line breaks do the punctuation.","","Girl, Woman, Other, chapters 1-4",40,"Read the first four chapters. Amma, a lesbian playwright, is about to open a play at the National Theatre. Her daughter Yazz is a university student navigating identity politics in the age of social media. Their friend Dominique moves to America with a controlling woman. Evaristo writes without periods — the sentences flow across line breaks. The effect is musical: each character has a different rhythm. The novel spans decades without ever leaving the present tense.",["British","Fiction","Contemporary","21st Century"],"bernardine-evaristo"),

mk("AUTHORS","Author","Alice Munro","Canadian short story writer who won the Nobel Prize in 2013 — the only short story writer to win the prize as a pure short story writer (not also a novelist). Her stories are set in rural Ontario and span entire lifetimes in 30 pages. She stopped writing in 2013 due to dementia. Her stories work like time machines: a gesture in the present opens a door to 40 years ago.","","Dear Life, the first 4 stories",38,"Read the first four stories. 'To Reach Japan' — a poet on a train to Toronto makes a decision that will define her marriage. Munro's stories don't build to epiphanies; they reveal that the epiphany happened years ago and the character is only now understanding it. Notice the temporal leaps — Munro covers decades in a paragraph and a single afternoon in 10 pages. Time is her medium, not plot.",["Canadian","Fiction","Short Stories","20th Century"],"alice-munro"),

mk("AUTHORS","Author","Milan Kundera","Czech-French novelist who wrote 'The Unbearable Lightness of Being'","","The Joke, the first section",30,"Read the first section of Kundera's debut novel (1967). Ludvik, a university student, writes a joke on a postcard to his girlfriend: 'Optimism is the opium of the people.' He's expelled from the Communist Party, sent to a penal battalion, and his life is derailed by a joke. Kundera writes ideology as farce with fatal consequences. The novel was banned in Czechoslovakia after the 1968 Soviet invasion.",["Czech","Fiction","Political","20th Century"],"milan-kundera-joke"),

mk("AUTHORS","Author","Zora Neale Hurston","African American novelist and anthropologist whose 'Their Eyes Were Watching God' (1937) was out of print and forgotten for decades before Alice Walker resurrected it in 1975. Hurston studied anthropology at Barnard with Franz Boas and conducted fieldwork in Haiti and Jamaica. She died in poverty in 1960 and was buried in an unmarked grave.","","Their Eyes Were Watching God, chapters 1-6",40,"Read the first six chapters. Janie Crawford returns to Eatonville and tells her story to her best friend Pheoby. Hurston writes in two registers: the frame narration in lyrical standard English, Janie's dialogue in Black Southern vernacular. Janie's grandmother marries her off at 16 to an old farmer. 'She had been summoned to behold a revelation.' Hurston's Janie is seeking not a man but a horizon — a life big enough for her soul.",["American","Fiction","Harlem Renaissance","20th Century"],"zora-neale-hurston"),

mk("AUTHORS","Author","Richard Wright","African American novelist whose 'Native Son' (1940) was the first novel by a Black author chosen by the Book of the Month Club — it sold 215,000 copies in three weeks. Wright fled America for Paris in 1947, tired of racism. His memoir 'Black Boy' (1945) describes his childhood hunger — literal and metaphorical — in the Jim Crow South.","","Native Son, Book One: Fear",42,"Read Book One. Bigger Thomas, a 20-year-old Black man in 1930s Chicago, gets a job as a chauffeur for a wealthy white family. On his first night, he accidentally kills the daughter and panics — the rest follows with the logic of a nightmare. Wright wrote Native Son as a protest novel: Bigger is what racism makes. Notice the claustrophobia — every scene is a room Bigger can't escape, even before the crime.",["American","Fiction","Protest Literature","20th Century"],"richard-wright"),

mk("AUTHORS","Author","Langston Hughes","African American poet, novelist, and playwright who was a leader of the Harlem Renaissance. His poem 'The Negro Speaks of Rivers' was written when he was 17, crossing the Mississippi by train. He wrote jazz poetry and columns for the Chicago Defender. His first novel 'Not Without Laughter' (1930) won the Harmon Gold Medal for literature.","","Selected Poems, the first 10 poems",22,"Read the first 10 poems. 'The Negro Speaks of Rivers' — 'I've known rivers ancient as the world and older than the flow of human blood in human veins.' Hughes wrote it on an envelope. His poetry is musical — the blues inform every line. 'I, Too' answers Whitman: 'I, too, sing America.' Notice the simplicity that's not simple — each poem is a door into a larger history. 'What happens to a dream deferred?'",["American","Poetry","Harlem Renaissance","20th Century"],"langston-hughes"),

mk("AUTHORS","Author","Flannery O'Connor","Southern Gothic writer from Georgia who raised peacocks and died of lupus at 39. Her 31 short stories and 2 novels are populated by Bible salesmen, escaped convicts, and self-righteous old women — all of whom encounter violence as a form of grace. She was a devout Catholic in the Protestant South, and her fiction is theology by other means.","","A Good Man Is Hard to Find, plus 3 other stories",30,"Read 'A Good Man Is Hard to Find' and three others. A grandmother manipulates her family into a detour to see a nonexistent plantation; they encounter an escaped convict called The Misfit. O'Connor's violence arrives with comic timing and theological weight: 'She would have been a good woman if it had been somebody there to shoot her every minute of her life.' Notice how her characters' self-deception is dismantled by brutality.",["American","Fiction","Southern Gothic","20th Century"],"flannery-oconnor"),

mk("AUTHORS","Author","Charles Baudelaire","French poet whose 'Les Fleurs du Mal' (1857) was prosecuted for obscenity — six poems were banned and Baudelaire was fined. His prose poems 'Le Spleen de Paris' invented a genre. He translated Poe into French. He died of syphilis at 46 after years of debt, opium, and paralysis. His poetry found beauty in decay: the city, the corpse, the prostitute.","","Paris Spleen, the first 10 prose poems",22,"Read the first 10 prose poems. 'Be always drunken. On wine, on poetry, or on virtue, as you wish.' Baudelaire's prose poems are fragments of urban life — a window, a crowd, an old woman, a dog. The form was new: poetry without verse. Notice how each prose poem captures a moment and explodes it into philosophy. The city is a 'hospital, prison, brothel, purgatory, hell' — and also the only place where beauty is possible.",["French","Poetry","Modernist","19th Century"],"charles-baudelaire"),

mk("AUTHORS","Author","Bram Stoker","Irish novelist who wrote 'Dracula' (1897) — the epistolary novel that invented modern vampire mythology. Stoker was the business manager of the Lyceum Theatre in London and Henry Irving's personal assistant. He researched Eastern European folklore for seven years before writing Dracula. He died poor, and the novel didn't become the monster hit until the 1922 film Nosferatu (which his widow sued and tried to destroy).","","Dracula, chapters 1-5",35,"Read the first five chapters. Jonathan Harker travels to Transylvania to finalize a real estate deal with Count Dracula — his journal entries become increasingly panicked as he realizes he's a prisoner. The novel is told entirely through documents: letters, diary entries, newspaper clippings. Stoker invented the modern vampire: no reflection, sleeps in a coffin, repelled by garlic and the cross. Notice the xenophobic subtext — Dracula is Eastern European, bringing contamination to pure English blood.",["Irish","Fiction","Gothic","19th Century"],"bram-stoker"),
]
total += append_batch("authors.json", a4, "AUTHORS")[0]
print(f"Total added so far: {total}")

# ===== BOOKS BATCH 4 (38) =====
print("\n--- Books Batch 4 ---")
b4 = [
mk("BOOKS","Book","Crime and Punishment (1866)","Dostoevsky's psychological thriller about Raskolnikov, a destitute student who murders a pawnbroker. The novel was published in installments in a magazine and readers mobbed the publisher's office for each chapter. Dostoevsky wrote it while gambling away his advance, and the urgency is on every page. Raskolnikov's guilt is not about the murder but about being ordinary.","Fyodor Dostoevsky","Crime and Punishment, Part One",48,"Read Part One. Raskolnikov tests his theory: some men (like Napoleon) can transgress moral law. The murder scene is a masterpiece of tension — the doorbell rings, and everything unravels. Dostoevsky makes St. Petersburg a character: yellow walls, stifling rooms, crowds that judge silently. Notice Raskolnikov's fever dreams — they're the novel's moral compass.",["Russian","Fiction","Psychological","19th Century"],"crime-and-punishment"),

mk("BOOKS","Book","Giovanni's Room (1956)","James Baldwin's novel about an American man in Paris torn between his girlfriend and an Italian bartender named Giovanni. Baldwin's publisher told him to burn the manuscript — it would ruin his career as a 'Negro' writer. He published anyway. The novel's narrator, David, is white, which was deliberate: Baldwin didn't want the novel dismissed as merely a 'Black' or 'gay' story.","James Baldwin","Giovanni's Room, the whole novel",42,"Read the whole novel — it's under 200 pages. David waits in the south of France for a train. Giovanni is about to be executed. Baldwin writes desire and self-loathing in the same sentence: David loves Giovanni and hates himself for it. The room of the title is where Giovanni hides David from the world — it becomes a tomb. Notice how Baldwin never lets David off the hook. The ending is a mirror.",["American","Fiction","Literary","20th Century"],"giovannis-room"),

mk("BOOKS","Book","Normal People (2018)","Sally Rooney's novel about Marianne and Connell — he's the popular son of a cleaner, she's the weird rich girl. They pretend not to know each other at school, then meet again at Trinity College. The novel is about class, intimacy, and the words they can't say. The BBC adaptation broke viewing records.","Sally Rooney","Normal People, chapters 1-5",35,"Read the first five chapters. Connell's mother cleans Marianne's house. At school, they don't speak. Rooney writes without quotation marks, letting dialogue bleed into narration. The sex scenes are explicit and tender — they're where the characters are most honest. Notice the power shifts: in high school Marianne is beneath Connell; at Trinity the roles reverse. Class is not just money; it's who gets to speak and who has to listen.",["Irish","Fiction","Contemporary","21st Century"],"normal-people"),

mk("BOOKS","Book","The Fire Next Time (1963)","James Baldwin's book-length essay in the form of two letters — one to his 14-year-old nephew, one from 'a region of my mind.' Published in The New Yorker, it became an instant classic. Baldwin writes that 'God gave Noah the rainbow sign, No more water, the fire next time!' — the title is a warning. The essay is a diagnosis of American racism from the inside, written with love and fury.","James Baldwin","The Fire Next Time, the whole book",30,"Read the whole book — it's short but every sentence is loaded. Baldwin's letter to his nephew: 'You were born where you were born and faced the future that you faced because you were black and for no other reason.' The second essay is about his experience with the Nation of Islam and his realization that Christianity and Islam are both failing Black America. Notice the balance of tenderness and rage — Baldwin never sacrifices one for the other.",["American","Essays","Nonfiction","20th Century"],"the-fire-next-time"),

mk("BOOKS","Book","Dubliners (1914)","James Joyce's collection of 15 short stories about Dublin in the early 20th century. Each story is a portrait of paralysis — the characters can't escape their city, their jobs, their memories. Joyce spent 10 years fighting publishers over the word 'bloody.' The collection ends with 'The Dead,' widely considered the greatest short story in English.","James Joyce","Dubliners, the first 7 stories",38,"Read the first seven stories. 'Araby' — a boy promises to bring a gift from a bazaar to a girl he barely knows. When he arrives as the stalls are closing, his romantic fantasy collapses. Joyce called these stories 'epiphanies' — moments when a character suddenly understands something about their life. Notice how little happens: the drama is interior. The paralysis is not just Dublin's; it's the human condition.",["Irish","Fiction","Short Stories","20th Century"],"dubliners"),

mk("BOOKS","Book","The Passion According to G.H. (1964)","Clarice Lispector's novel about a wealthy woman in Rio de Janeiro who enters her maid's room and crushes a cockroach — and from that act, has a mystical crisis that dissolves her entire sense of self. The novel is less a story than an extended meditation. Lispector described it as 'the best book I wrote, and I don't understand it.'","Clarice Lispector","The Passion According to G.H., the whole novel",40,"Read the whole novel — it's short but intense. G.H. (she is never fully named) enters the room that her maid has just left. Everything is clean, white, and terrifyingly empty. The cockroach is ancient, pre-human. When its white paste oozes out, G.H. eats it — and the world dissolves. Lispector's prose is a sustained panic attack: the sentences fragment, circle back, ask questions they can't answer. The novel is about the horror of being alive.",["Brazilian","Fiction","Philosophical","20th Century"],"the-passion-according-to-gh"),

mk("BOOKS","Book","Season of Migration to the North (1966)","Tayeb Salih's novel about a Sudanese man who returns from studying in England to find a stranger, Mustafa Sa'eed, has settled in his village. Mustafa Sa'eed's story is Conrad's 'Heart of Darkness' reversed — the 'savage' goes to Europe and conquers it through seduction. The Arab Literary Academy named it the greatest Arabic novel of the 20th century.","Tayeb Salih","Season of Migration to the North, chapters 1-5",40,"Read the first five chapters. The narrator discovers Mustafa Sa'eed, a mysterious older man who quotes English poetry in a Sudanese village. Sa'eed's story emerges: a brilliant student sent to England who seduced English women as revenge for colonialism and was tried for murder of a woman he drove to suicide. Salih's prose is hypnotic — the Nile flows through every page. The novel asks: can the colonized ever go home?",["Sudanese","Fiction","Postcolonial","20th Century"],"season-of-migration-to-the-north"),

mk("BOOKS","Book","A Visit from the Goon Squad (2010)","Jennifer Egan's novel told in 13 interlinked stories, including one chapter written entirely as a PowerPoint presentation. It spans from the 1970s punk scene to a near-future New York, following Bennie Salazar, a record executive, and Sasha, his kleptomaniac assistant. Won the Pulitzer. Time is the 'goon squad' — it takes everything eventually.","Jennifer Egan","A Visit from the Goon Squad, chapters 1-4",38,"Read the first four chapters. Sasha steals a wallet on a date. Bennie sprays gold flakes in his coffee and can't feel music anymore. Each chapter shifts perspective and time, but characters recur in the background. The PowerPoint chapter (Chapter 12) is not a gimmick — each slide is a short story. Egan writes the music industry as a metaphor for aging: everyone's trying to stay relevant as time closes in.",["American","Fiction","Literary","21st Century"],"a-visit-from-the-goon-squad"),

mk("BOOKS","Book","Pachinko (2017)","Min Jin Lee's multi-generational novel about a Korean family in Japan from 1910 to the 1980s. Koreans in Japan — Zainichi — were treated as permanent foreigners even after generations. The novel was rejected by every major publisher before becoming a National Book Award finalist. The title refers to pachinko parlors — one of the few businesses Zainichi Koreans could own.","Min Jin Lee","Pachinko, Book I",50,"Read Book I. Sunja, a teenager in a Korean fishing village, becomes pregnant by a married yakuza. A Christian minister offers to marry her and take her to Japan. Lee embeds the history of Japanese colonization of Korea in the smallest domestic moments: a bowl of rice, a boarding house, the registry that marks Koreans as aliens. The novel spans three generations; each one carries the weight of the previous.",["Korean-American","Historical Fiction","Literary","21st Century"],"pachinko-novel"),

mk("BOOKS","Book","The Canterbury Tales (c. 1400)","Geoffrey Chaucer's collection of 24 stories told by pilgrims traveling to Canterbury Cathedral. Each pilgrim tells a tale — knight, miller, wife of Bath, pardoner — in their own voice. Chaucer wrote in Middle English when that was revolutionary: French and Latin were the languages of literature. He died before finishing it; the tales we have are a fragment.","Geoffrey Chaucer","The Canterbury Tales, the General Prologue + 3 tales",48,"Read the General Prologue and three tales: The Knight's Tale, The Miller's Tale, and The Wife of Bath's Tale. Each pilgrim is introduced in a portrait of startling vividness — the Prioress who feeds her dogs better than the poor, the Friar who's more pimp than priest. The Miller's Tale is a fabliau about a cuckolded carpenter — it's filthy and hilarious. Notice the Wife of Bath: she's been married five times and has the best argument for female sovereignty in medieval literature.",["British","Poetry","Classic","Medieval"],"the-canterbury-tales"),

mk("BOOKS","Book","The Sympathizer (2015)","Viet Thanh Nguyen's Pulitzer-winning novel, already described above.","Viet Thanh Nguyen","The Sympathizer, full novel","","",[],"sympathizer-dupe",0),  # Placeholder, never processed
mk("BOOKS","Book","Austerlitz (2001)","W.G. Sebald's final novel about a man who arrives in England on a Kindertransport at age 4 and doesn't learn his real name or origin until he's retired. The novel is narrated as a series of conversations, accompanied by uncaptioned photographs — they feel like evidence but prove nothing. Sebald died in a car crash weeks after finishing it.","W.G. Sebald","Austerlitz, the whole novel",50,"Read the whole novel — it's one long paragraph punctuated by photographs. Jacques Austerlitz, an architectural historian, tells his story to the narrator in train stations and cafes across Europe. He was a child refugee from Prague; his mother died in Theresienstadt. Sebald's sentences are immense — they hold decades in one breath. The photographs are uncaptioned: a building, a boy in a costume, a pair of eyes. They haunt the text without explaining it.",["German","Fiction","Historical","21st Century"],"austerlitz"),

mk("BOOKS","Book","A Wizard of Earthsea (1968)","Ursula K. Le Guin's fantasy novel about a boy named Ged who goes to a wizard school and releases a shadow monster in an act of pride. He spends the rest of the novel being hunted by his own darkness. Le Guin wrote it as a response to the lack of non-white heroes in fantasy — all the characters in Earthsea are brown-skinned. It was published decades before Harry Potter and says more about the danger of magical power in 200 pages than Rowling does in 7 books.","Ursula K. Le Guin","A Wizard of Earthsea, the whole novel",42,"Read the whole novel. Ged, a goatherd with a gift for magic, is trained at the school of Roke. In a duel of pride, he summons a shadow from the land of the dead. The shadow pursues him; eventually he realizes he must stop running and turn to face it. The novel is structured like a Taoist parable: the shadow is Ged's own death, and naming it is the only way to be free. Le Guin's magic has moral weight — every spell has consequences.",["American","Fantasy","Young Adult","20th Century"],"a-wizard-of-earthsea"),

mk("BOOKS","Book","The Bluest Eye (1970)","Toni Morrison's debut novel about Pecola Breedlove, a Black girl who prays for blue eyes, believing they will make her beautiful and loved. The novel is told in fragments — from multiple perspectives, across years — because Pecola's trauma can't be narrated in a straight line. Morrison wrote it while working as an editor at Random House, getting up at 4 AM to write before her children woke.","Toni Morrison","The Bluest Eye, the whole novel",45,"Read the whole novel. The novel opens with a Dick-and-Jane primer that fractures into nonsense — the safe white world is breaking apart. Pecola's story is told by Claudia, a girl who survives what Pecola doesn't. Morrison shows racism as a poison that turns inward: Pecola believes if she had blue eyes, she would be beautiful. The novel's tragedy is not just what happens to Pecola but that her community participates in destroying her.",["American","Fiction","Literary","20th Century"],"the-bluest-eye"),

mk("BOOKS","Book","Braiding Sweetgrass (2013)","Robin Wall Kimmerer's book about indigenous wisdom and botany. Kimmerer is a Potawatomi botanist and professor who bridges western science and Native knowledge. Each chapter weaves together ecology, storytelling, and memoir. The title comes from the Potawatomi story of Skywoman, who brought plants to earth. The book was a slow-burn bestseller that became a phenomenon years after publication.","Robin Wall Kimmerer","Braiding Sweetgrass, Part One: Planting Sweetgrass",42,"Read Part One. Kimmerer begins with Skywoman falling from the sky, creating Turtle Island with a handful of mud. Then she describes pecans, strawberries, and the grammar of animacy in Potawatomi — English treats the natural world as 'it'; Potawatomi treats it as someone. Notice how Kimmerer refuses to choose between science and spirituality: they are two languages for the same love. 'In some Native languages the term for plants translates to those who take care of us.'",["Native American","Nonfiction","Nature","21st Century"],"braiding-sweetgrass"),

mk("BOOKS","Book","On Earth We're Briefly Gorgeous (2019)","Ocean Vuong's debut novel written as a letter from a Vietnamese-American son to his illiterate mother. Vuong is a poet, and the novel reads like a long poem — every sentence is chiseled. It moves between the Vietnam War, a nail salon in Hartford, and a first love with a white boy in tobacco fields. The novel is autobiographical in spirit but Vuong insists it's fiction.","Ocean Vuong","On Earth We're Briefly Gorgeous, Part One",38,"Read Part One. 'Let me begin again.' Little Dog writes to his mother Rose, who cannot read. He describes his grandmother Lan, who escaped an arranged marriage during the war, and his first love, Trevor, who taught him to drive a combine harvester. Vuong writes about the body — his mother's hands scarred from the nail salon, Trevor's body in the tobacco fields — as the site where love and violence are the same thing. The monarch butterfly is the novel's recurring image: migration, transformation, fragile beauty.",["Vietnamese-American","Fiction","Literary","21st Century"],"on-earth-were-briefly-gorgeous"),

mk("BOOKS","Book","If Beale Street Could Talk (1974)","James Baldwin's novel about a young Black couple in 1970s Harlem — Tish and Fonny. Fonny is in prison for a rape he didn't commit, and Tish is pregnant with his child. The novel is narrated by Tish, whose voice is steady and fierce. Baldwin wrote it as a love story, not a protest novel — but love under racism is protest. Adapted into an Oscar-winning film in 2018.","James Baldwin","If Beale Street Could Talk, the whole novel",40,"Read the whole novel. Tish tells Fonny — and us — how they fell in love. She's 19 and pregnant; her family rallies around Fonny while his own family fractures. Baldwin writes love as the only resistance that matters: Tish's family pools their money for lawyers, brings food, holds each other. The novel is about the carceral system but never lets the system overshadow the people. Tish's narration is the novel's miracle — she's never bitter, only certain.",["American","Fiction","Romance","20th Century"],"if-beale-street-could-talk"),

mk("BOOKS","Book","The Vaster Wilds (2023)","Lauren Groff's novel about a servant girl who escapes a 17th-century colonial settlement in Virginia during a famine and runs into the wilderness with nothing but her wits. The novel is a survival story and a spiritual crisis told in prose that feels like scripture. Groff wrote it in a fever during the pandemic.","Lauren Groff","The Vaster Wilds, Part One",38,"Read Part One. A girl known only as 'the girl' or 'the servant' flees the Jamestown settlement in the dead of winter. She has no name because she was never given one that mattered. The wilderness is violent — wolves, starvation, exposure — but also holy. Groff's prose is stripped to its essentials: every sentence is physical. The girl's spiritual crisis intensifies as she starves: she sees God in a flash of light on ice and questions whether God has ever seen her.",["American","Historical Fiction","Literary","21st Century"],"the-vaster-wilds"),

mk("BOOKS","Book","The Alchemist (1988)","Paulo Coelho's allegorical novel about Santiago, a Spanish shepherd who dreams of treasure at the pyramids. The novel was a slow seller at first — Coelho's first publisher dropped him — but has now sold over 65 million copies in 80+ languages. It's one of the best-selling books in history and the most translated book by a living author.","Paulo Coelho","The Alchemist, Part One",25,"Read Part One. Santiago sells his sheep and sails to Tangier. He's robbed, works for a crystal merchant, and joins a caravan crossing the Sahara. Coelho writes in simple declarative sentences — the prose feels like folklore. 'When you want something, all the universe conspires in helping you to achieve it.' The novel is less a plot than a parable: the treasure was never at the pyramids. Notice the alchemist himself appears only in the last third.",["Brazilian","Fiction","Allegorical","20th Century"],"the-alchemist"),

mk("BOOKS","Book","The Bee Sting (2023)","Paul Murray's novel about the Barnes family — an Irish family unraveling after the 2008 financial crash. The novel is structured in four parts, each from a different family member's perspective. It was shortlisted for the Booker Prize. The novel is funny, devastating, and 650 pages that feel like 300.","Paul Murray","The Bee Sting, Part One: Cass",42,"Read Part One. Cass Barnes, 17, is drinking in the woods with her friend Elaine when the novel opens. Her father's car dealership is failing; her mother is selling things on eBay; her brother is building a bunker. Murray writes Irish family life with comic precision and then turns the screw: the financial crash is a slow-motion car wreck that everyone sees coming and no one can stop. The bee sting of the title is both literal and metaphorical.",["Irish","Fiction","Contemporary","21st Century"],"the-bee-sting"),

mk("BOOKS","Book","The Midnight Library (2020)","Matt Haig's novel about Nora Seed, who tries to kill herself and finds herself in a library between life and death — each book contains a different version of her life she could have lived. The novel is about regret and the paths not taken. Haig wrote it after his own mental health crisis and it became a global bestseller.","Matt Haig","The Midnight Library, the whole novel",38,"Read the whole novel. Nora lands in the Midnight Library presided over by her old school librarian Mrs. Elm. She can try any life — Olympic swimmer, rock star, glaciologist, mother — and if she finds one worth living, she stays. The premise is simple but Haig executes it with empathy: each life teaches Nora something about the one she already has. The novel's philosophy is not 'anything is possible' but 'what you have is already enough.'",["British","Fiction","Speculative","21st Century"],"the-midnight-library"),

mk("BOOKS","Book","Kindred (1979)","Octavia Butler's novel about Dana, a Black woman in 1976 Los Angeles who is suddenly transported to a Maryland plantation in 1815. She is pulled back in time whenever her white ancestor Rufus is in mortal danger — she must keep him alive long enough to father her ancestor. Butler called it 'grim fantasy' — there's no explanation for the time travel, just the unflinching reality of slavery.","Octavia Butler","Kindred, the whole novel",48,"Read the whole novel. Dana's first trip to the past: she saves a drowning white boy named Rufus and is nearly shot by his father. The time travel is involuntary and brutal — Dana arrives disoriented and returns with injuries. Butler doesn't romanticize the past: Dana must live as a slave, and the novel documents the daily violence without flinching. Rufus grows from a frightened boy into a slaveholder who believes he owns Dana. The horror is not the time travel; it's history.",["American","Science Fiction","Historical","20th Century"],"kindred"),

mk("BOOKS","Book","Yellowface (2023)","R.F. Kuang's novel about June Hayward, a white writer who steals her dead Chinese-American friend's manuscript and publishes it as her own — complete with an ethnically ambiguous author photo. What follows is a satire of the publishing industry, cancel culture, and literary appropriation. The novel went viral on BookTok and became a bestseller.","R.F. Kuang","Yellowface, the whole novel",35,"Read the whole novel. Athena Liu dies choking on a pancake in front of June, who takes her unpublished manuscript about Chinese laborers in WWI. June edits it, changes her name to Juniper Song, and becomes a literary star. The novel works as thriller and satire: June's narration is a masterclass in self-justification. Kuang makes you understand June even as you recoil. The publishing industry — sensitivity readers, Twitter pile-ons, diversity panels — is skewered with insider knowledge.",["American","Fiction","Satire","21st Century"],"yellowface"),

mk("BOOKS","Book","The Sellout (2015)","Paul Beatty's novel about a Black man who reinstates slavery and segregation in his Los Angeles neighborhood — as satire — and ends up in the Supreme Court. Won the Booker Prize (the first American to win it). Every sentence is a joke that's serious. Beatty's narrator is an urban farmer who grows satsumas and watermelons and calls himself a 'sellout' for loving the neighborhood no one else cares about.","Paul Beatty","The Sellout, chapters 1-8",38,"Read the first eight chapters. The narrator (unnamed) is raised by a sociologist father who used him as a subject in racial psychology experiments. His father is shot by the police, and the narrator's response is absurdity: he takes a slave, paints a line of segregation on the street. Beatty's prose is hip-hop and literature at once — dense with references, profane, hilarious. The satire is so sharp it hurts: the novel is about how race is simultaneously everything and nothing.",["American","Fiction","Satire","21st Century"],"the-sellout"),

mk("BOOKS","Book","Don Quixote (1605/1615)","Cervantes' novel about a man who reads so many chivalric romances that he decides to become a knight-errant. It's the first modern novel and invented metafiction: the characters in Part Two have read Part One. Nabokov called it 'the cruelest book ever written' because everyone laughs at Quixote's madness. Cervantes published Part One at 58 after a life of captivity, excommunication, and failure.","Miguel de Cervantes","Don Quixote, chapters 1-10",48,"Read the first ten chapters. Alonso Quijano renames himself Don Quixote, makes a helmet out of pasteboard, and rides out on a broken-down horse. His first battle: windmills he thinks are giants. Sancho Panza, a peasant, becomes his squire on the promise of an island. Cervantes writes Quixote's madness with tenderness — the knight sees what we wish the world contained. The innkeeper who knights him is humoring a fool, but the ceremony is real to Quixote.",["Spanish","Fiction","Classic","17th Century"],"don-quixote"),

mk("BOOKS","Book","Their Eyes Were Watching God (1937)","Zora Neale Hurston's novel about Janie Crawford's journey through three marriages to selfhood in rural Florida. Out of print for decades, rescued in 1975 by Alice Walker, who put a gravestone on Hurston's unmarked grave. The novel is written in lyrical third person and Black Southern dialect — the two registers are the novel's music.","Zora Neale Hurston","Their Eyes Were Watching God, chapters 1-6",40,"Read the first six chapters. Janie returns to Eatonville and tells her story. Her grandmother marries her off at 16 — she 'had been summoned to behold a revelation.' Janie's journey is toward the horizon: not a man but a self. Hurston's prose is incantatory: 'Ships at a distance have every man's wish on board.' The hurricane section is one of the most terrifying passages in American literature. Janie survives it all — and the novel ends with her pulling in her horizon 'like a great fish-net.'",["American","Fiction","Harlem Renaissance","20th Century"],"their-eyes-were-watching-god"),
]
total += append_batch("books.json", b4, "BOOKS")[0]
print(f"Total added so far: {total}")
